/*
 * Que efeito cada habilidade usa, escolhido uma a uma.
 *
 * As regras por palavra (vfxProfiles.ts) acertam o tema, mas com 250 lutadores
 * metade das habilidades caía em "corte", "soco" ou "escudo". Aqui cada
 * habilidade marcante ganha a família que conta a história dela: o Azul do
 * Gojo puxa, o Vermelho empurra, o Vazio Infinito abre um domínio; o Hakai
 * desintegra; o Chidori canta; a Galick Gun é uma onda de ki. O que não está
 * aqui (marcado com "-") continua com a regra por palavra.
 *
 * Cada linha: as famílias das habilidades 0, 1 e 2 do personagem.
 */
import type { VfxFamily } from './vfxProfiles';

const T: Record<string, string> = {
  goku: 'kamehameha kaioken instinto', vegeta: 'kamehameha transformacao -', naruto: 'clones_naruto rasengan modo_kurama',
  sasuke: 'chidori_sasuke amaterasu genjutsu_sasuke', luffy: 'gomu_gatling corpo_de_borracha gear_fifth_nika', gojo: 'atracao repulsao dominio',
  light: 'olho marca death_note', pikachu: '- raio_em_cadeia velocidade', saitama: 'soco_casual resgate soco_serio',
  wolverine: 'garras armadura regeneracao', batman: 'marca disco escudo_tech', superman: 'visao_de_calor eu_te_seguro ultimo_filho_de_krypton',
  spiderman: 'lancar_teia salvamento_aranha teia_de_impacto', hulk: 'hulk_esmaga rugido_do_hulk mais_forte_ainda', thor: 'martelo tempestade raio_em_cadeia',
  strange: 'barreira_magica relogio portal', flash: 'soco_relampago resgate velocidade', wonderwoman: 'chicote escudo_fisico investida',
  ironman: 'repulsor escudo_tech canhao_de_energia', captain: 'disco escudo_fisico grito_de_guerra', magneto: 'metal metal gravidade',
  deadpool: 'pow_cartoon confusao regeneracao', raven: 'runas sombra corvo_da_alma', thanos: 'manopla relogio desintegrar',
  gohan: 'golpe_do_potencial feixe kamehameha', piccolo: 'makankosappo escudo_do_mentor regeneracao_namekiana', frieza: 'disco laser transformacao',
  kakashi: 'sharingan_kakashi raikiri kamui', itachi: 'lua_vermelha corvos susanoo', sakura: 'controle_de_chakra forca_monstruosa byakugou',
  tanjiro: 'marca lamina_de_agua lamina_de_fogo', nezuko: 'sangue chute_demoniaco transformacao', zenitsu: 'iaido velocidade lamina_eletrica',
  inosuke: 'olho garras investida', muzan: 'tentaculos acido regeneracao', yuji: 'punho_divergente punho_amaldicoado -',
  megumi: 'inv_cao tempestade -', nobara: 'facas maldicao explosao', sukuna: 'desmanche corte_vertical mil_cortes',
  ichigo: '- transformacao lamina_sombria', rukia: 'espinho_de_gelo nevasca bloco_de_gelo', aizen: 'hipnose sarcofago olho',
  kenpachi: 'espadao corte_vertical transformacao', eren: 'soco_titanico armadura rugido', mikasa: 'investida - iaido',
  levi: 'marca - -', gon: 'jajanken_pedra jajanken_tesoura jajanken_papel', killua: 'ritmo_eletrico palma_relampago velocidade_divina',
  hisoka: 'esticar cartas teia', kurapika: 'corrente corrente olho', edward: 'espinhos_de_terra runas punho_transmutado',
  alphonse: 'armadura cura_em_area barreira_magica', roy: 'estalo_de_dedos chuva_de_meteoros labareda', guts: 'matadora_de_dragoes armadura -',
  griffith: 'marca grito_de_guerra asa_negra', jotaro: 'inv_ora rajada_de_golpes relogio', dio: 'muda facas relogio',
  giorno: 'soco_da_vida barreira_magica cura_em_area', denji: 'motosserra sangue mil_cortes', power: '- pancada_de_sangue sangue',
  makima: 'olho corrente hipnose', frieren: 'runas feitico_comum encanto', anya: 'olho resgate -',
  loid: 'clones silencio velocidade', yor: 'agulha_de_espinho chute_voador petalas', jinwoo: 'invocacao grito_de_guerra inv_sombras',
  kaneki: 'kagune mordida tentaculos', yugi: 'cartas inv_mago carta_magica', kaiba: 'carta_dragao inv_dragao supernova',
  blackpanther: 'armadura garras_cineticas repulsao', scarletwitch: 'sorte - fenda', vision: 'teleporte laser pulso_emp',
  antman: 'atracao enxame soco_de_pym', captainmarvel: 'cosmico hadouken supernova', daredevil: 'marca bastao bastao',
  punisher: 'marca espingarda tiro_preciso', ghostrider: 'corrente_flamejante olho labareda', blade: 'marca iaido -',
  moonknight: 'lua disco raio_divino', storm: 'tornado raio_em_cadeia tempestade', cyclops: 'rajada_de_contencao ricochete_optico feixe_concentrado',
  jeangrey: '- barreira_magica fenix', rogue: 'toque_absorvente - clones', gambit: 'cartas cartas bastao',
  professorx: 'olho hipnose silencio', venom: 'tentaculo_simbionte mordida tentaculos', carnage: 'lamina_viva sangue mil_cortes',
  doctordoom: 'laser pentagrama canhao_de_energia', loki: 'adaga_ilusoria teleporte hipnose', ultron: 'pulso_emp escudo_tech laser',
  greengoblin: 'bomba gas foguete', silversurfer: 'cosmico velocidade fenda', galactus: '- cosmico toque_do_devorador',
  starlord: 'blasters_elementais grito_de_guerra confete', groot: 'vinhas regeneracao vinhas', rocket: 'bomba foguete arma_grande',
  aquaman: 'tridente agua tsunami', greenlantern: 'escudo_fisico punho_gigante martelo', cyborg: 'pulso_emp canhao_sonico laser',
  shazam: 'raio_divino grito_de_guerra encanto', cloud: 'golpe_ascendente postura_de_guarda omnislash', tifa: 'exposto - -',
  sephiroth: 'masamune lamina_sombria asa_negra', kratos: 'laminas_kratos furia_espartana ira_dos_deuses', link: 'espada_mestra escudo_fisico -',
  zelda: 'selo barreira_magica flecha', ganondorf: 'faisca_negra runas raio_divino', samus: 'marca missil esfera_carregada',
  dante: 'rebellion_e_ebony saraivada transformacao', vergil: 'iaido corte_dimensional mil_cortes', bayonetta: 'chute_giratorio relogio inv_gomorrah',
  masterchief: 'escudo_tech saraivada pisao', doomslayer: 'investida armadura espinhos_de_terra', snake: 'teleporte tiro_preciso cqc',
  raidenmgr: 'lamina_eletrica mil_cortes iaido', leon: '- tiro_preciso corte_vertical', jill: 'cura grito_de_guerra armadura',
  wesker: 'teleporte rajada_de_golpes olho', lara: 'flecha - tiro_preciso', ezio: 'clones lamina_oculta -',
  sonic: 'spin_dash investida transformacao', shadowhh: 'flecha relogio chuva_de_meteoros', megaman: 'tiro_do_buster arma_adquirida carga_maxima',
  zeromm: 'z_saber iaido mil_cortes', mario: 'pisada_do_mario - estrela_invencivel', bowser: 'investida sopro_de_fogo terremoto',
  ryu: 'hadouken shoryuken canhao_de_energia', chunli: 'chute_relampago chute_giratorio repulsao', akuma: 'hadouken teleporte shun_goku_satsu',
  scorpion: 'kunai_do_inferno teleporte sopro_de_fogo', subzero: '- bloco_de_gelo nevasca', liukang: 'chute_do_dragao - dragao',
  raidenmk: 'tempestade barreira_magica raio_divino', jin: '- chute_voador asa_negra', kazuya: 'pisao laser transformacao',
  sora: 'keyblade - grito_de_guerra', tuob: 'corte_giratorio laser espadao', sekiro: 'escudo_fisico iaido execucao',
  malenia: '- lamina_protetica petalas', agent47: 'clones chicote tiro_preciso', arthas: 'ceifadora_de_almas erguer_os_mortos praga_da_carne',
  geralt: 'barreira_magica sopro_de_fogo hipnose', isaac: 'cortador_de_plasma lentidao corte_vertical', gordon: 'bastao arma_da_gravidade repulsao',
  hayabusa: 'iaido tornado esmagar', pyramidhead: 'grande_faca medo -', kirby: 'atracao encanto tornado',
  donkeykong: 'soco_giratorio barril_arremessado batida_do_gorila', simonbelmont: 'chicote agua_benta disco', princeofpersia: 'adaga_do_tempo relogio areia',
  alucardcv: 'espada_de_alucard teleporte caveira', seiya: 'meteoros_de_pegaso cosmico investida', majinbuu: 'laser regeneracao pow_cartoon',
  kuririn: 'kienzan taiyoken kame_kuririn', shiryu: 'escudo_fisico colera_do_dragao pilar', hyoga: 'poeira_de_diamante execucao_aurora zero_absoluto',
  shun: 'corrente tornado corrente', ikki: 'ave_fenix golpe_fantasma renascimento', saga: 'cosmico fenda hipnose',
  shaka: 'tesouro_do_ceu todo_poderoso seis_mundos', aiolia: 'relampago_de_plasma velocidade_da_luz rugido_do_leao', camus: 'nevasca bloco_de_gelo espinho_de_gelo',
  hadescz: 'dominio medo caveira', madara: 'susanoo_perfeito meteoro_madara mugen_tsukuyomi', pain: 'gravidade rinnegan buraco_negro',
  minato: 'teleporte esfera_espiral marca', gaara: 'areia areia areia', trunks: 'espada_do_futuro burning_attack corte_final',
  cell: '- regeneracao supernova', broly: 'esfera_carregada transformacao rugido', beerus: 'toque_da_destruicao - repulsao',
  mewtwo: '- barreira_magica hipnose', charizard: 'lanca_chamas garra_de_dragao explosao_de_fogo', garou: 'lamina_de_agua chute_giratorio garras',
  genos: 'canhao_de_energia foguete pulso_emp', yusuke: 'soco_espiritual reigun rei_shotgun', hiei: 'lamina_de_fogo olho dragao',
  sailormoon: 'tiara_lunar purificacao ressurreicao', coringa: 'gas cartas bomba', arlequina: 'marretada chute_giratorio bomba',
  darkseid: 'laser punho_de_apokolips hipnose', lexluthor: 'canhao radiacao enfraquecimento', spawn: 'corrente tentaculos labareda',
  invencivel: '- investida pow_cartoon', omniman: 'punho_gigante investida sangue', leonardo: '- grito_de_guerra investida',
  raphael: 'sais investida pow_cartoon', donatello: 'bastao pulso_emp escudo_tech', michelangelo: 'nunchakus chute_giratorio confete',
  constantine: 'pentagrama raio_divino caveira', hellboy: 'mao_da_perdicao armadura martelo', picapau: 'confusao bicada confusao',
  pernalonga: 'teleporte clones bonk', ben10: 'golpe_alienigena labareda investida', aang: 'rajada_do_aang dobra_de_agua estado_avatar_aang',
  samuraijack: 'iaido purificacao corte_vertical', heman: 'espadao tenho_a_forca espadao', popeye: 'soco_de_marinheiro lanche rajada_de_golpes',
  optimus: 'escudo_tech laser grito_de_guerra', salsicha: 'velocidade lanche bonk', bobesponja: 'bolhas esticar karate',
  scooby: 'bonk lanche sorte', rick: 'portal pulso_emp radiacao', finn: '- investida confete',
  megatron: 'canhao_de_energia punho_gigante medo', docinho: 'investida - supernova', mickey: 'encanto inv_vassouras confete',
  donald: 'pow_cartoon rugido -', pateta: 'bonk confusao sorte', stitch: '- mordida pow_cartoon',
  buzz: 'laser pulso_emp foguete', woody: 'laco grito_de_guerra confete', srincrivel: 'investida escudo_fisico punho_gigante',
  mulherelastica: 'esticar escudo_fisico resgate', frozone: '- bloco_de_gelo nevasca', korra: 'sopro_de_fogo espinhos_de_terra estado_avatar',
  zuko: 'lamina_de_fogo raio_em_cadeia corte_cruzado', azula: 'fogo_azul - florete', toph: 'visao_sismica muralha_de_terra metal_dobrado',
  iroh: 'lanche raio_em_cadeia sopro_de_fogo', patolino: 'confusao mordida bomba', taz: 'tornado mordida atracao',
  coiote: 'bomba bonk foguete', papaleguas: 'investida areia velocidade', marvin: 'bomba laser desintegrar',
  tom: 'pow_cartoon investida garras', jerry: 'bonk teleporte marretada', pantera: 'silencio clones teleporte',
  shredder: 'garras investida mil_cortes', splinter: '- bastao bonk', krang: 'inv_androide escudo_tech -',
  caseyjones: 'bastao - pow_cartoon', bebop: 'investida golpe_pesado pisao', skeletor: 'cajado_da_caveira - dominio',
  shera: 'raio_divino grito_de_guerra chute_voador', liono: 'espada_de_augurio olho tempestade', cheetara: 'bastao investida florete',
  mummra: 'antigos_espiritos forma_desperta retorno_ao_sarcofago', homer: 'bonk lanche pow_cartoon', bart: 'estilingue confusao bomba',
  peter: 'pow_cartoon bomba confusao', stewie: 'laser escudo_tech dominio', cartman: 'rugido enfraquecimento gas',
  billcipher: 'runas fenda olho', plankton: 'inv_clones pulso_emp -', mojojojo: 'punho_gigante laser rugido',
  capitaoplaneta: 'barreira_magica vinhas grito_de_guerra', bugiganga: 'esticar rajada_de_ar confusao', dannyphantom: 'raio_fantasma teleporte rugido',
  coragem: 'medo resgate bencao',
};

export const FAMILIA_DA_HABILIDADE: Record<string, VfxFamily> = Object.fromEntries(
  Object.entries(T).flatMap(([id, linha]) => linha.split(' ').flatMap((f, i) => (f === '-' ? [] : [[`${id}:${i}`, f as VfxFamily]]))),
);

/*
 * A criatura de cada invocador (parte 8): a mesma animação e o mesmo som quando
 * ela chega (a habilidade) e a cada ataque dela. O Caminho Deva do Pain segue
 * com a gravidade; o Caminho Animal aparece nos ataques da invocação.
 */
export const FAMILIA_DA_INVOCACAO: Record<string, VfxFamily> = {
  megumi: 'inv_cao', jinwoo: 'inv_sombras', yugi: 'inv_mago', kaiba: 'inv_dragao', bayonetta: 'inv_gomorrah',
  jotaro: 'inv_ora', pain: 'inv_feras', mickey: 'inv_vassouras', plankton: 'inv_clones', krang: 'inv_androide',
};

/*
 * O ataque básico com nome próprio (src/data/basicos.ts) usa o efeito que bate
 * com o nome: o Escudo arremessado do Capitão voa e quica, a Martelada do Thor
 * é martelo, o Dardo crescente do Cavaleiro da Lua é disco, as kunais do
 * Kakashi e do Minato são facas, o Estilingue do Bart é tiro.
 *
 * O ataque básico de quem tem um jeito próprio de bater: o espadachim corta, o
 * atirador atira, o telepata empurra com a mente. Os outros seguem a regra
 * (as próprias habilidades e o visual do personagem).
 */
export const FAMILIA_DO_BASICO: Record<string, VfxFamily> = {
  toph: 'pedra_da_toph',
  akuma: 'soco',
  agent47: 'tiro',
  arthas: 'frostmourne',
  geralt: 'corte_diagonal',
  donkeykong: 'golpe_pesado',
  beerus: 'soco_basico',
  yusuke: 'soco_basico',
  constantine: 'runas',
  aang: 'bastao',
  rick: 'laser',
  azula: 'chute_basico',
  iroh: 'soco_basico',
  papaleguas: 'bicada',
  marvin: 'laser',
  pantera: 'bonk',
  skeletor: 'bastao',
  shera: 'corte_diagonal',
  billcipher: 'chama_do_triangulo',
  dannyphantom: 'soco_basico',
  naruto: 'soco_basico',
  batman: 'batarangue',
  spiderman: 'teia_e_soco',
  deadpool: 'corte_cruzado',
  frieza: 'chicote',
  inosuke: 'laminas_serrilhadas',
  aizen: 'corte',
  hisoka: 'cartas',
  kurapika: 'soco_basico',
  griffith: 'florete',
  jotaro: 'soco_do_stand',
  makima: 'dedo_apontado',
  frieren: 'bastao',
  jinwoo: 'adaga_de_kamish',
  scarletwitch: 'magia_do_caos',
  storm: 'vento',
  cyclops: 'feixe',
  jeangrey: 'telecinese',
  professorx: 'golpe_psiquico',
  loki: 'estocada',
  aquaman: 'soco_basico',
  cloud: 'espadao',
  samus: 'canhao_de_braco',
  bayonetta: 'saraivada',
  wesker: 'golpe_sobre_humano',
  sonic: 'spin_attack',
  shadowhh: 'chute_basico',
  megaman: 'tiro',
  luffy: 'esticar',
  light: 'olho',
  thor: 'martelo',
  flash: 'soco_basico',
  wonderwoman: 'bracelete',
  captain: 'escudo_do_capitao',
  magneto: 'metal',
  thanos: 'soco_basico',
  kakashi: 'facas',
  itachi: 'shuriken',
  nezuko: 'chute_basico',
  megumi: 'soco_basico',
  levi: 'corte',
  killua: 'garras_de_killua',
  alphonse: 'golpe_pesado',
  yugi: 'cartas',
  kaiba: 'cartas',
  vision: 'laser',
  punisher: 'tiro',
  moonknight: 'dardo_crescente',
  gambit: 'bastao',
  doctordoom: 'soco_basico',
  ultron: 'soco_basico',
  greengoblin: 'soco_basico',
  silversurfer: 'feixe',
  starlord: 'tiro',
  groot: 'soco_basico',
  greenlantern: 'soco_basico',
  cyborg: 'soco_basico',
  shazam: 'soco_basico',
  tifa: 'soco_basico',
  zelda: 'luz',
  ganondorf: 'soco_basico',
  masterchief: 'tiro',
  doomslayer: 'espingarda',
  leon: 'tiro',
  jill: 'tiro',
  lara: 'duas_pistolas',
  bowser: 'garras',
  isaac: 'pisao',
  gordon: 'tiro',
  kirby: 'soco_basico',
  seiya: 'soco_basico',
  kuririn: 'soco_basico',
  hyoga: 'soco_basico',
  saga: 'soco_basico',
  shaka: 'rendicao',
  aiolia: 'soco_basico',
  camus: 'gelo',
  hadescz: 'lamina_sombria',
  minato: 'kunai_de_hiraishin',
  gaara: 'areia',
  cell: 'tentaculos',
  mewtwo: 'soco_basico',
  genos: 'soco_basico',
  sailormoon: 'chute_basico',
  coringa: 'flor_de_lapela',
  arlequina: 'taco_de_beisebol',
  lexluthor: 'laser',
  optimus: 'machado_de_energon',
  scooby: 'mordida_cartoon',
  megatron: 'soco_basico',
  mickey: 'soco_basico',
  stitch: 'garras',
  buzz: 'soco_basico',
  mulherelastica: 'esticar',
  korra: 'fogo',
  tom: 'frigideira',
  krang: 'laser',
  bebop: 'investida',
  mummra: 'sombra',
  bart: 'chute_basico',
  stewie: 'soco_basico',
  cartman: 'pow_cartoon',
  plankton: 'laser',
  mojojojo: 'soco_basico',
  capitaoplaneta: 'raio_de_gaia',
  coragem: 'mordida_cartoon',
  vegeta: 'soco_basico',
  goku: 'soco_basico',
  taz: 'mordida',
  gohan: 'soco_basico',
  piccolo: 'braco_namekiano',
  broly: 'punho_lendario',
  saitama: 'soco_basico',
  gojo: 'soco_basico',
  yuji: 'soco_basico',
  sukuna: 'soco_basico',
  pikachu: 'choque_do_pikachu',
  sasuke: 'kusanagi',
  sakura: 'soco_de_chakra',
  zenitsu: 'saque_do_trovao',
  nobara: 'martelo_e_prego',
  madara: 'leque_gunbai',
  pain: 'estocada',
  mikasa: 'laminas_odm',
  eren: 'soco_basico',
  gon: 'soco_basico',
  edward: 'soco_basico',
  roy: 'tiro',
  guts: 'flecha',
  giorno: 'soco_basico',
  power: 'soco_basico',
  anya: 'golpe_de_panico',
  loid: 'golpe_do_espiao',
  yor: 'chute_basico',
  kaneki: 'chute_basico',
  shiryu: 'punho_do_dragao',
  shun: 'corrente_de_andromeda',
  ikki: 'soco_basico',
  charizard: 'garras',
  superman: 'soco_de_aco',
  strange: 'disparo_arcano',
  ironman: 'soco_basico',
  raven: 'sombra',
  antman: 'soco_basico',
  captainmarvel: 'punho_fotonico',
  ghostrider: 'soco_basico',
  rogue: 'soco_basico',
  venom: 'soco_basico',
  carnage: 'garras',
  galactus: 'soco_basico',
  rocket: 'tiro',
  blackpanther: 'garras',
  darkseid: 'soco_basico',
  hellboy: 'tiro',
  sephiroth: 'corte',
  kratos: 'soco_basico',
  link: 'corte_diagonal',
  dante: 'corte_diagonal',
  vergil: 'corte',
  snake: 'soco_basico',
  ezio: 'corte',
  zeromm: 'tiro',
  mario: 'soco_basico',
  chunli: 'chute_basico',
  scorpion: 'corte',
  liukang: 'soco_basico',
  kazuya: 'soco_do_diabo',
  sora: 'corte',
  sekiro: 'aparar_e_cortar',
  malenia: 'corte',
  pyramidhead: 'soco_basico',
  princeofpersia: 'corte',
  alucardcv: 'corte_diagonal',
  raphael: 'soco_basico',
  michelangelo: 'chute_basico',
  picapau: 'soco_basico',
  patolino: 'bicada',
  ben10: 'soco_basico',
  popeye: 'soco_basico',
  bobesponja: 'soco_basico',
  woody: 'soco_basico',
  coiote: 'bigorna',
  liono: 'soco_basico',
  homer: 'barrigada',
  bugiganga: 'gadget_surpresa',
  dio: 'soco_basico',
  garou: 'soco_basico',
  hiei: 'corte',
  hulk: 'soco_do_hulk',
  tanjiro: 'corte',
  muzan: 'garras',
  ichigo: 'corte',
  kenpachi: 'corte_diagonal',
  denji: 'soco_basico',
  blade: 'corte',
  raidenmgr: 'corte',
  subzero: 'soco_basico',
  jin: 'soco_basico',
  tuob: 'corte',
  hayabusa: 'corte',
  simonbelmont: 'facas',
  spawn: 'soco_basico',
  invencivel: 'soco_basico',
  leonardo: 'corte',
  donatello: 'chute_basico',
  samuraijack: 'corte',
  heman: 'soco_basico',
  docinho: 'soco_basico',
  frozone: 'soco_basico',
  zuko: 'chute_basico',
  shredder: 'soco_basico',
  caseyjones: 'soco_basico',
};
