/*
 * As famílias novas de efeito (122), desenhadas em Python em
 * tools/vfx/familias_v2 e com um som próprio cada uma (tools/audio/sfx_familias.py).
 *
 * Cada uma diz as folhas que usa (impacto, e às vezes viagem, faixa ou preparo),
 * o tamanho, quanto tempo dura, a cor de base e como a cor do personagem
 * entra; e o som: o impacto é sempre o som da própria família.
 */
import type { Familia } from './vfxProfiles';

type F = Omit<Familia, 'cor' | 'tinta' | 'escala' | 'tempo'> & Partial<Pick<Familia, 'cor' | 'tinta' | 'escala' | 'tempo'>>;
const n = (x: F): Familia => ({ escala: 1.9, tempo: 0.75, cor: '#dff1ff', tinta: 'personagem', ...x });

export const FAMILIAS_NOVAS = {
  // ------------------------------------------------------------ corpo
  chute_voador: n({ nome: 'Chute voador', grupo: 'físico', impacto: 'chute_voador', escala: 2.0, tempo: 0.65, cor: '#ffd9a8' }),
  chute_giratorio: n({ nome: 'Chute giratório', grupo: 'físico', impacto: 'chute_giratorio', escala: 2.1, cor: '#ffd9a8' }),
  bonk: n({ nome: 'Pancada de desenho', grupo: 'físico', impacto: 'bonk', escala: 1.9, tempo: 0.85, cor: '#ffe28a', tinta: 'elemento' }),
  pow_cartoon: n({ nome: 'POW!', grupo: 'físico', impacto: 'pow_cartoon', escala: 1.8, tempo: 0.7, cor: '#ffe066', tinta: 'elemento' }),
  martelo: n({ nome: 'Martelada', grupo: 'físico', impacto: 'martelo', escala: 2.2, tempo: 0.8, cor: '#ffd9a8' }),
  corrente: n({ nome: 'Corrente', grupo: 'físico', impacto: 'corrente', escala: 2.1, tempo: 0.9, cor: '#d8e4f0' }),
  marretada: n({ nome: 'Marretada de desenho', grupo: 'físico', impacto: 'marretada', escala: 2.2, tempo: 0.9, cor: '#ffcf8a', tinta: 'elemento' }),
  investida: n({ nome: 'Investida', grupo: 'físico', impacto: 'investida', escala: 2.1, tempo: 0.7, cor: '#ffc28a' }),
  punho_gigante: n({ nome: 'Punho gigante', grupo: 'físico', impacto: 'punho_gigante', escala: 2.2, tempo: 0.8, cor: '#ffc28a' }),
  soco_serio: n({ nome: 'Soco sério', grupo: 'físico', impacto: 'soco_serio', escala: 2.5, tempo: 0.9, cor: '#fff3d6', tinta: 'fixa' }),
  faisca_negra: n({ nome: 'Faísca negra', grupo: 'físico', impacto: 'faisca_negra', escala: 2.1, tempo: 0.7, cor: '#ff3355', tinta: 'fixa' }),
  chicote: n({ nome: 'Chicote', grupo: 'físico', impacto: 'chicote', escala: 2.1, tempo: 0.7 }),
  garras: n({ nome: 'Garras', grupo: 'corte', impacto: 'garras', escala: 2.1, tempo: 0.75, cor: '#e6f4ff' }),
  mordida: n({ nome: 'Mordida', grupo: 'físico', impacto: 'mordida', escala: 1.9, tempo: 0.7, cor: '#ffd9d9' }),
  bastao: n({ nome: 'Bastão', grupo: 'físico', impacto: 'bastao', escala: 2.0, tempo: 0.75, cor: '#ffd9a8' }),
  tentaculos: n({ nome: 'Tentáculos', grupo: 'físico', impacto: 'tentaculos', escala: 2.2, tempo: 0.85, cor: '#d04a6a' }),
  pisao: n({ nome: 'Pisão', grupo: 'físico', impacto: 'pisao', escala: 2.3, tempo: 0.85, cor: '#e8b77c' }),
  esticar: n({ nome: 'Braço elástico', grupo: 'físico', impacto: 'esticar', escala: 2.1, tempo: 0.8, cor: '#ffd9a8' }),
  // ------------------------------------------------------------ cortes
  corte_vertical: n({ nome: 'Corte vertical', grupo: 'corte', acento: 'soco', impacto: 'corte_vertical', escala: 2.2 }),
  iaido: n({ nome: 'Saque rápido', grupo: 'corte', impacto: 'iaido', escala: 2.3, tempo: 0.85 }),
  mil_cortes: n({ nome: 'Mil cortes', grupo: 'corte', impacto: 'mil_cortes', escala: 2.3, tempo: 0.9 }),
  espadao: n({ nome: 'Espadão', grupo: 'corte', impacto: 'espadao', escala: 2.4, tempo: 0.85 }),
  lamina_de_fogo: n({ nome: 'Lâmina de fogo', grupo: 'corte', impacto: 'lamina_de_fogo', escala: 2.3, cor: '#ff7a2e', tinta: 'elemento' }),
  lamina_eletrica: n({ nome: 'Lâmina elétrica', grupo: 'corte', impacto: 'lamina_eletrica', escala: 2.3, cor: '#ffe76a', tinta: 'elemento' }),
  lamina_sombria: n({ nome: 'Lâmina sombria', grupo: 'corte', impacto: 'lamina_sombria', escala: 2.3, cor: '#9a5cff', tinta: 'elemento' }),
  motosserra: n({ nome: 'Motosserra', grupo: 'corte', impacto: 'motosserra', escala: 2.0, tempo: 0.85, cor: '#ffb070' }),
  lamina_de_agua: n({ nome: 'Lâmina de água', grupo: 'corte', impacto: 'lamina_de_agua', escala: 2.3, tempo: 0.85, cor: '#4fb4ff', tinta: 'elemento' }),
  disco: n({ nome: 'Disco arremessado', grupo: 'projétil', viagem: 'disco', impacto: 'ricochete', escala: 1.9, tempo: 0.65 }),
  florete: n({ nome: 'Estocadas finas', grupo: 'corte', impacto: 'florete', escala: 2.1, tempo: 0.8 }),
  // ------------------------------------------------------------ projéteis
  flecha: n({ nome: 'Flecha', grupo: 'projétil', viagem: 'flecha', impacto: 'cravar', aponta: true, escala: 1.6, tempo: 0.6 }),
  tiro_preciso: n({ nome: 'Tiro de precisão', grupo: 'projétil', viagem: 'tiro', impacto: 'tiro_preciso', escala: 1.8, tempo: 0.7, cor: '#ffe0a0' }),
  espingarda: n({ nome: 'Espingarda', grupo: 'projétil', viagem: 'saraivada', impacto: 'espingarda', escala: 1.9, tempo: 0.7, cor: '#ffe0a0' }),
  teia: n({ nome: 'Teia', grupo: 'projétil', viagem: 'teia_bola', impacto: 'teia_rede', escala: 1.9, tempo: 0.9, cor: '#f2f7ff', tinta: 'fixa' }),
  bolhas: n({ nome: 'Bolhas', grupo: 'elemento', impacto: 'bolhas', escala: 1.9, tempo: 0.9, cor: '#7fd6ff', tinta: 'elemento' }),
  cartas: n({ nome: 'Cartas', grupo: 'projétil', viagem: 'cartas_voando', impacto: 'cartas_explosivas', escala: 2.0, tempo: 0.85, cor: '#ff7ad1' }),
  facas: n({ nome: 'Facas', grupo: 'projétil', viagem: 'facas_voando', impacto: 'cravar', escala: 1.7, tempo: 0.6, cor: '#e6f4ff' }),
  foguete: n({ nome: 'Foguete', grupo: 'projétil', viagem: 'foguete', impacto: 'explosao_grande', escala: 2.3, tempo: 0.85, cor: '#ffb070' }),
  bomba: n({ nome: 'Bomba', grupo: 'projétil', viagem: 'bomba', impacto: 'explosao_cartoon', escala: 2.1, tempo: 0.85, cor: '#ffb070' }),
  canhao: n({ nome: 'Bala de canhão', grupo: 'projétil', viagem: 'bala_de_canhao', impacto: 'explosao_grande', escala: 2.2, tempo: 0.85, cor: '#ffb070' }),
  gas: n({ nome: 'Gás', grupo: 'elemento', impacto: 'gas', escala: 2.1, tempo: 0.95, cor: '#9be84a', tinta: 'elemento' }),
  laser: n({ nome: 'Laser', grupo: 'energia', faixa: 'laser', impacto: 'queimadura', escala: 1.6, tempo: 0.6, cor: '#ff4a4a' }),
  // ------------------------------------------------------------ energia
  hadouken: n({ nome: 'Bola de ki', grupo: 'energia', viagem: 'bola_ki', impacto: 'explosao_ki', escala: 1.9, tempo: 0.7, cor: '#8fd8ff' }),
  kamehameha: n({ nome: 'Onda de ki', grupo: 'energia', preparo: 'carga_ki', faixa: 'feixe_ki', impacto: 'explosao_ki', escala: 2.3, tempo: 0.85, cor: '#5ec8ff' }),
  canhao_de_energia: n({ nome: 'Canhão de energia', grupo: 'energia', preparo: 'carga', faixa: 'canhao_de_energia', impacto: 'explosao_ki', escala: 2.3, tempo: 0.85, cor: '#9fe6ff' }),
  esfera_espiral: n({ nome: 'Esfera espiral', grupo: 'energia', preparo: 'carga_ki', impacto: 'esfera_espiral', escala: 2.0, tempo: 0.9, cor: '#7fd8ff' }),
  buraco_negro: n({ nome: 'Buraco negro', grupo: 'energia', impacto: 'buraco_negro', escala: 2.2, tempo: 0.95, cor: '#a07cff' }),
  gravidade: n({ nome: 'Gravidade', grupo: 'energia', impacto: 'gravidade', escala: 2.2, tempo: 0.9, cor: '#b48cff' }),
  cosmico: n({ nome: 'Cosmos', grupo: 'energia', impacto: 'cosmico', escala: 2.2, tempo: 0.9, cor: '#c7a2ff' }),
  chuva_de_meteoros: n({ nome: 'Chuva de meteoros', grupo: 'energia', impacto: 'chuva_de_meteoros', escala: 2.3, tempo: 0.95, cor: '#ffd08a' }),
  supernova: n({ nome: 'Supernova', grupo: 'energia', impacto: 'supernova', escala: 2.4, tempo: 0.9, cor: '#fff0b0' }),
  pulso_emp: n({ nome: 'Pulso eletromagnético', grupo: 'energia', impacto: 'pulso_emp', escala: 2.0, tempo: 0.8, cor: '#7fe7ff', tinta: 'elemento' }),
  pilar: n({ nome: 'Pilar de energia', grupo: 'energia', impacto: 'pilar', escala: 2.2, tempo: 0.9 }),
  transformacao: n({ nome: 'Transformação', grupo: 'energia', impacto: 'transformacao', escala: 2.2, tempo: 0.95, cor: '#ffe66b' }),
  atracao: n({ nome: 'Atração', grupo: 'energia', impacto: 'atracao', escala: 2.1, tempo: 0.9, cor: '#4aa8ff' }),
  repulsao: n({ nome: 'Repulsão', grupo: 'energia', impacto: 'repulsao', escala: 2.2, tempo: 0.8, cor: '#ff4a4a' }),
  dominio: n({ nome: 'Domínio', grupo: 'especial', impacto: 'dominio', escala: 2.4, tempo: 0.95, cor: '#b48cff' }),
  desintegrar: n({ nome: 'Desintegrar', grupo: 'especial', impacto: 'desintegrar', escala: 2.1, tempo: 0.95, cor: '#c7a2ff', tinta: 'fixa' }),
  // ------------------------------------------------------------ elementos
  labareda: n({ nome: 'Labareda', grupo: 'elemento', impacto: 'labareda', escala: 2.2, tempo: 0.9, cor: '#ff7a2e', tinta: 'elemento' }),
  sopro_de_fogo: n({ nome: 'Sopro de fogo', grupo: 'elemento', impacto: 'sopro_de_fogo', escala: 2.2, tempo: 0.9, cor: '#ff8a3a', tinta: 'elemento' }),
  fenix: n({ nome: 'Fênix', grupo: 'elemento', impacto: 'fenix', escala: 2.3, tempo: 0.9, cor: '#ff9a3a', tinta: 'elemento' }),
  chama_negra: n({ nome: 'Chama negra', grupo: 'elemento', impacto: 'chama_negra', escala: 2.1, tempo: 0.95, cor: '#6a3cff', tinta: 'fixa' }),
  dragao: n({ nome: 'Dragão', grupo: 'elemento', atravessa: 'dragao_faixa', impacto: 'dragao', escala: 2.3, tempo: 0.9, cor: '#ff8a3a' }),
  nevasca: n({ nome: 'Nevasca', grupo: 'elemento', impacto: 'nevasca', escala: 2.2, tempo: 0.95, cor: '#bfefff', tinta: 'elemento' }),
  bloco_de_gelo: n({ nome: 'Bloco de gelo', grupo: 'elemento', impacto: 'bloco_de_gelo', escala: 1.9, tempo: 0.95, cor: '#8fe6ff', tinta: 'elemento' }),
  espinho_de_gelo: n({ nome: 'Espinho de gelo', grupo: 'elemento', impacto: 'espinho_de_gelo', escala: 2.1, tempo: 0.85, cor: '#8fe6ff', tinta: 'elemento' }),
  tempestade: n({ nome: 'Tempestade', grupo: 'elemento', impacto: 'tempestade', escala: 2.3, tempo: 0.95, cor: '#ffe76a', tinta: 'elemento' }),
  raio_em_cadeia: n({ nome: 'Raio em cadeia', grupo: 'elemento', impacto: 'raio_em_cadeia', escala: 2.2, tempo: 0.8, cor: '#ffe76a', tinta: 'elemento' }),
  chidori: n({ nome: 'Mil pássaros', grupo: 'elemento', impacto: 'chidori', escala: 2.1, tempo: 0.85, cor: '#9fd8ff' }),
  tsunami: n({ nome: 'Tsunami', grupo: 'elemento', impacto: 'tsunami', escala: 2.4, tempo: 0.95, cor: '#4fb4ff', tinta: 'elemento' }),
  areia: n({ nome: 'Areia', grupo: 'elemento', impacto: 'areia', escala: 2.1, tempo: 0.95, cor: '#e8c47c', tinta: 'elemento' }),
  espinhos_de_terra: n({ nome: 'Espinhos de terra', grupo: 'elemento', impacto: 'espinhos_de_terra', escala: 2.3, tempo: 0.85, cor: '#d6a86a', tinta: 'elemento' }),
  metal: n({ nome: 'Metal', grupo: 'elemento', impacto: 'metal', escala: 2.0, tempo: 0.9, cor: '#c9d6e3', tinta: 'elemento' }),
  tornado: n({ nome: 'Tornado', grupo: 'elemento', impacto: 'tornado', escala: 2.3, tempo: 0.95, cor: '#bff5e4', tinta: 'elemento' }),
  rajada_de_ar: n({ nome: 'Rajada de ar', grupo: 'elemento', impacto: 'rajada_de_ar', escala: 2.1, tempo: 0.8, cor: '#bff5e4', tinta: 'elemento' }),
  vinhas: n({ nome: 'Vinhas', grupo: 'elemento', impacto: 'vinhas', escala: 2.0, tempo: 0.95, cor: '#7ed957', tinta: 'elemento' }),
  petalas: n({ nome: 'Pétalas', grupo: 'elemento', impacto: 'petalas', escala: 2.1, tempo: 0.95, cor: '#ff7aa8', tinta: 'elemento' }),
  enxame: n({ nome: 'Enxame', grupo: 'elemento', impacto: 'enxame', escala: 2.0, tempo: 0.95, cor: '#ffcf5a' }),
  acido: n({ nome: 'Ácido', grupo: 'elemento', impacto: 'acido', escala: 1.9, tempo: 0.95, cor: '#b6f04a', tinta: 'elemento' }),
  sangue: n({ nome: 'Sangue', grupo: 'elemento', impacto: 'sangue', escala: 2.0, tempo: 0.85, cor: '#e2334a', tinta: 'fixa' }),
  radiacao: n({ nome: 'Radiação', grupo: 'elemento', impacto: 'radiacao', escala: 2.0, tempo: 0.95, cor: '#7dff6a', tinta: 'fixa' }),
  lua: n({ nome: 'Lua', grupo: 'elemento', impacto: 'lua', escala: 2.1, tempo: 0.95, cor: '#dfe8ff', tinta: 'elemento' }),
  raio_divino: n({ nome: 'Raio divino', grupo: 'elemento', impacto: 'raio_divino', escala: 2.3, tempo: 0.9, cor: '#ffe9a3', tinta: 'elemento' }),
  rugido: n({ nome: 'Rugido', grupo: 'físico', impacto: 'rugido', escala: 2.2, tempo: 0.85 }),
  // ------------------------------------------------------------ magia
  olho: n({ nome: 'Olho', grupo: 'magia', impacto: 'olho', escala: 2.1, tempo: 0.95, cor: '#ff5a5a' }),
  hipnose: n({ nome: 'Hipnose', grupo: 'magia', impacto: 'hipnose', escala: 2.0, tempo: 0.95, cor: '#d18cff' }),
  relogio: n({ nome: 'Tempo', grupo: 'magia', impacto: 'relogio', escala: 2.1, tempo: 0.95, cor: '#ffe9a3' }),
  runas: n({ nome: 'Runas', grupo: 'magia', impacto: 'runas', escala: 2.1, tempo: 0.95, cor: '#c7a2ff' }),
  sarcofago: n({ nome: 'Sarcófago', grupo: 'magia', impacto: 'sarcofago', escala: 2.0, tempo: 0.95, cor: '#9a7cff' }),
  encanto: n({ nome: 'Encanto', grupo: 'magia', impacto: 'encanto', escala: 2.0, tempo: 0.9, cor: '#ffe9a3' }),
  caveira: n({ nome: 'Caveira', grupo: 'magia', impacto: 'caveira', escala: 2.0, tempo: 0.95, cor: '#b6ffcf' }),
  clones: n({ nome: 'Clones', grupo: 'magia', impacto: 'clones', escala: 2.1, tempo: 0.95 }),
  teleporte: n({ nome: 'Teleporte', grupo: 'magia', impacto: 'teleporte', escala: 2.0, tempo: 0.8 }),
  fenda: n({ nome: 'Fenda dimensional', grupo: 'magia', impacto: 'fenda', escala: 2.2, tempo: 0.95, cor: '#8f9dff' }),
  sorte: n({ nome: 'Sorte', grupo: 'magia', impacto: 'sorte', escala: 2.0, tempo: 0.95, cor: '#ffe066', tinta: 'elemento' }),
  confete: n({ nome: 'Confete', grupo: 'especial', impacto: 'confete', escala: 2.1, tempo: 0.95, cor: '#ffd36b' }),
  confusao: n({ nome: 'Confusão', grupo: 'magia', impacto: 'confusao', escala: 2.0, tempo: 0.95, cor: '#ffe066', tinta: 'elemento' }),
  clarao_solar: n({ nome: 'Clarão solar', grupo: 'especial', impacto: 'clarao_solar', escala: 2.2, tempo: 0.8, cor: '#fff6c8', tinta: 'fixa' }),
  pentagrama: n({ nome: 'Pentagrama', grupo: 'magia', impacto: 'pentagrama', escala: 2.2, tempo: 0.95, cor: '#ff4a3a', tinta: 'elemento' }),
  invocacao: n({ nome: 'Invocação', grupo: 'magia', impacto: 'invocacao', escala: 2.1, tempo: 0.95 }),
  lua_vermelha: n({ nome: 'Lua vermelha', grupo: 'especial', impacto: 'lua_vermelha', escala: 2.3, tempo: 0.95, cor: '#ff3a3a', tinta: 'fixa' }),
  susanoo: n({ nome: 'Guerreiro espectral', grupo: 'especial', impacto: 'susanoo', escala: 2.4, tempo: 0.95, cor: '#a07cff' }),
  asa_negra: n({ nome: 'Asa negra', grupo: 'magia', impacto: 'asa_negra', escala: 2.2, tempo: 0.95, cor: '#8a7cff' }),
  // ------------------------------------------------------------ apoio e Status
  cura_em_area: n({ nome: 'Cura em área', grupo: 'apoio', impacto: 'cura_em_area', escala: 2.0, tempo: 0.95, cor: '#7dffb0', tinta: 'fixa' }),
  regeneracao: n({ nome: 'Regeneração', grupo: 'apoio', impacto: 'regeneracao', escala: 1.9, tempo: 0.95, cor: '#7dffb0', tinta: 'fixa' }),
  grito_de_guerra: n({ nome: 'Grito de guerra', grupo: 'apoio', impacto: 'grito_de_guerra', escala: 2.0, tempo: 0.9, cor: '#ffd36b', tinta: 'elemento' }),
  velocidade: n({ nome: 'Velocidade', grupo: 'apoio', impacto: 'velocidade', escala: 1.9, tempo: 0.9, cor: '#bff5e4', tinta: 'elemento' }),
  escudo_tech: n({ nome: 'Escudo tecnológico', grupo: 'apoio', impacto: 'escudo_tech', escala: 1.8, tempo: 0.95, cor: '#7fe7ff', tinta: 'elemento' }),
  barreira_magica: n({ nome: 'Barreira mágica', grupo: 'apoio', impacto: 'barreira_magica', escala: 1.9, tempo: 0.95, cor: '#c7a2ff', tinta: 'elemento' }),
  escudo_fisico: n({ nome: 'Escudo de mão', grupo: 'apoio', impacto: 'escudo_fisico', escala: 1.8, tempo: 0.85, cor: '#8edeff', tinta: 'elemento' }),
  armadura: n({ nome: 'Armadura', grupo: 'apoio', impacto: 'armadura', escala: 1.8, tempo: 0.95, cor: '#c9d6e3', tinta: 'elemento' }),
  resgate: n({ nome: 'Resgate', grupo: 'apoio', impacto: 'resgate', escala: 1.9, tempo: 0.9, cor: '#8edeff', tinta: 'elemento' }),
  bencao: n({ nome: 'Bênção', grupo: 'apoio', impacto: 'bencao', escala: 2.0, tempo: 0.95, cor: '#ffe9a3', tinta: 'fixa' }),
  lanche: n({ nome: 'Lanche', grupo: 'apoio', impacto: 'lanche', escala: 1.8, tempo: 0.95, cor: '#ffcf8a', tinta: 'fixa' }),
  ressurreicao: n({ nome: 'Ressurreição', grupo: 'apoio', impacto: 'ressurreicao', escala: 2.4, tempo: 1.0, cor: '#ffe08a', tinta: 'fixa' }),
  renascer: n({ nome: 'Renascer', grupo: 'elemento', impacto: 'renascer', escala: 2.5, tempo: 1.0, cor: '#ff9a3a', tinta: 'fixa' }),
  copia: n({ nome: 'Copiar', grupo: 'apoio', impacto: 'copia', escala: 1.9, tempo: 1.0, cor: '#ff5a5a', tinta: 'fixa' }),
  esquiva: n({ nome: 'Esquiva', grupo: 'apoio', impacto: 'esquiva', escala: 1.8, tempo: 1.0, cor: '#c8f7ff', tinta: 'fixa' }),
  ultima_resistencia: n({ nome: 'Última resistência', grupo: 'apoio', impacto: 'ultima_resistencia', escala: 2.2, tempo: 1.0, cor: '#ffd36b', tinta: 'fixa' }),
  sono: n({ nome: 'Sono', grupo: 'apoio', impacto: 'sono', escala: 1.8, tempo: 1.0, cor: '#b9b8ff', tinta: 'fixa' }),
  cegueira: n({ nome: 'Cegueira', grupo: 'apoio', impacto: 'cegueira', escala: 1.8, tempo: 1.0, cor: '#fff3c4', tinta: 'fixa' }),
  dissipar: n({ nome: 'Dissipar', grupo: 'apoio', impacto: 'dissipar', escala: 1.9, tempo: 1.0, cor: '#c3a6ff', tinta: 'fixa' }),
  reflexo: n({ nome: 'Reflexo', grupo: 'apoio', impacto: 'reflexo', escala: 1.8, tempo: 1.0, cor: '#9fdcff', tinta: 'fixa' }),
  espinhos: n({ nome: 'Espinhos', grupo: 'apoio', impacto: 'espinhos', escala: 1.8, tempo: 1.0, cor: '#a6d36a', tinta: 'fixa' }),
  vampirismo: n({ nome: 'Vampirismo', grupo: 'apoio', impacto: 'vampirismo', escala: 1.8, tempo: 1.0, cor: '#ff4f6e', tinta: 'fixa' }),
  provocar: n({ nome: 'Provocar', grupo: 'apoio', impacto: 'provocar', escala: 1.8, tempo: 1.0, cor: '#ff6a46', tinta: 'fixa' }),
  brasas_renascendo: n({ nome: 'Renascendo', grupo: 'elemento', impacto: 'brasas_renascendo', escala: 1.9, tempo: 1.0, cor: '#ff8a3a', tinta: 'fixa' }),
  purificacao: n({ nome: 'Purificação', grupo: 'apoio', impacto: 'purificar_onda', escala: 1.9, tempo: 0.95, cor: '#e8fbff', tinta: 'fixa' }),
  enfraquecimento: n({ nome: 'Enfraquecimento', grupo: 'apoio', impacto: 'enfraquecer', escala: 1.9, tempo: 0.95, cor: '#b3a2c9', tinta: 'fixa' }),
  lentidao: n({ nome: 'Lentidão', grupo: 'apoio', impacto: 'lentidao', escala: 1.9, tempo: 0.95, cor: '#9fc3e0', tinta: 'fixa' }),
  marca: n({ nome: 'Marca', grupo: 'apoio', impacto: 'marca', escala: 1.9, tempo: 0.9, cor: '#ff5a5a', tinta: 'fixa' }),
  silencio: n({ nome: 'Silêncio', grupo: 'apoio', impacto: 'silencio', escala: 1.9, tempo: 0.95, cor: '#c3a2ff', tinta: 'fixa' }),
  medo: n({ nome: 'Medo', grupo: 'apoio', impacto: 'medo', escala: 2.0, tempo: 0.95, cor: '#c84aff', tinta: 'fixa' }),
  exposto: n({ nome: 'Guarda quebrada', grupo: 'apoio', impacto: 'exposto', escala: 1.9, tempo: 0.9, cor: '#ff9475', tinta: 'fixa' }),
  estrela_invencivel: n({ nome: 'Estrela invencível', grupo: 'especial', impacto: 'estrela_invencivel', escala: 2.0, tempo: 0.95, cor: '#ffe066', tinta: 'fixa' }),
  // ------------------------------------------------------------ invocações (cada criatura com a sua animação e o seu som)
  inv_cao: n({ nome: 'Cão divino', grupo: 'magia', impacto: 'inv_cao', escala: 2.4, tempo: 1.0, cor: '#9a86ff', tinta: 'fixa' }),
  inv_sombras: n({ nome: 'Soldados das sombras', grupo: 'magia', impacto: 'inv_sombras', escala: 2.5, tempo: 1.0, cor: '#8a5cff', tinta: 'fixa' }),
  inv_mago: n({ nome: 'Mago Negro', grupo: 'magia', impacto: 'inv_mago', escala: 2.5, tempo: 1.0, cor: '#b46bff', tinta: 'fixa' }),
  inv_dragao: n({ nome: 'Dragão Branco', grupo: 'energia', impacto: 'inv_dragao', escala: 2.6, tempo: 1.0, cor: '#cfeaff', tinta: 'fixa' }),
  inv_gomorrah: n({ nome: 'Gomorrah', grupo: 'magia', impacto: 'inv_gomorrah', escala: 2.4, tempo: 1.0, cor: '#ff4a6a', tinta: 'fixa' }),
  inv_ora: n({ nome: 'Star Platinum', grupo: 'físico', aponta: true, impacto: 'inv_ora', escala: 2.4, tempo: 1.0, cor: '#a98bff', tinta: 'fixa' }),
  inv_feras: n({ nome: 'Caminho Animal', grupo: 'magia', impacto: 'inv_feras', escala: 2.4, tempo: 1.0, cor: '#ffb070', tinta: 'fixa' }),
  inv_vassouras: n({ nome: 'Vassouras encantadas', grupo: 'especial', impacto: 'inv_vassouras', escala: 2.3, tempo: 1.0, cor: '#7fd6ff', tinta: 'fixa' }),
  inv_clones: n({ nome: 'Exército de clones', grupo: 'especial', impacto: 'inv_clones', escala: 2.2, tempo: 1.0, cor: '#5fe36b', tinta: 'fixa' }),
  inv_androide: n({ nome: 'Androide de combate', grupo: 'físico', aponta: true, impacto: 'inv_androide', escala: 2.3, tempo: 1.0, cor: '#ffb070', tinta: 'fixa' }),
  // ------------------------------------------------------------ golpes de assinatura (a cena da habilidade famosa, com som próprio)
  death_note: n({ nome: 'Death Note', grupo: 'especial', impacto: 'death_note', escala: 2.4, tempo: 1.0, cor: '#e24a5a', tinta: 'fixa' }),
  shoryuken: n({ nome: 'Shoryuken', grupo: 'físico', impacto: 'shoryuken', escala: 2.4, tempo: 0.95, cor: '#ff8a3a', tinta: 'fixa' }),
  punho_divergente: n({ nome: 'Punho divergente', grupo: 'físico', impacto: 'punho_divergente', escala: 2.3, tempo: 1.0, cor: '#6a9cff', tinta: 'fixa' }),
  agua_benta: n({ nome: 'Água benta', grupo: 'elemento', impacto: 'agua_benta', escala: 2.4, tempo: 1.0, cor: '#7fb8ff', tinta: 'fixa' }),
  kaioken: n({ nome: 'Kaioken', grupo: 'especial', impacto: 'kaioken', escala: 2.3, tempo: 1.0, cor: '#ff4a3a', tinta: 'fixa' }),
  instinto: n({ nome: 'Instinto Superior', grupo: 'especial', impacto: 'instinto', escala: 2.2, tempo: 1.0, cor: '#a3b4d4', tinta: 'fixa' }),
  corvos: n({ nome: 'Ilusão de corvos', grupo: 'magia', viagem: 'corvo_voando', impacto: 'corvos', escala: 2.4, tempo: 1.0, cor: '#9a86c8', tinta: 'fixa' }),
  shun_goku_satsu: n({ nome: 'Shun Goku Satsu', grupo: 'especial', impacto: 'shun_goku_satsu', escala: 2.4, tempo: 1.0, cor: '#ff4a6a', tinta: 'fixa' }),
  spin_dash: n({ nome: 'Spin Dash', grupo: 'físico', aponta: true, impacto: 'spin_dash', escala: 2.2, tempo: 0.95, cor: '#4a8cff', tinta: 'fixa' }),
  estado_avatar: n({ nome: 'Estado Avatar', grupo: 'especial', impacto: 'estado_avatar', escala: 2.4, tempo: 1.0, cor: '#7fd0ff', tinta: 'fixa' }),
  tenho_a_forca: n({ nome: 'Eu tenho a força', grupo: 'especial', impacto: 'tenho_a_forca', escala: 2.4, tempo: 1.0, cor: '#ffd35a', tinta: 'fixa' }),
  muda: n({ nome: 'MUDA MUDA', grupo: 'físico', aponta: true, impacto: 'inv_ora', escala: 2.4, tempo: 1.0, cor: '#ffd35a', tinta: 'fixa' }),
  // os jeitos de bater: o que o ataque básico faz além do golpe (BattleEffects, por cima do golpe)
  quique: n({ nome: 'Ricochete', grupo: 'projétil', impacto: 'quique', escala: 1.9, tempo: 1.0, cor: '#ffb35c', tinta: 'fixa' }),
  golpe_largo: n({ nome: 'Golpe largo', grupo: 'físico', impacto: 'golpe_largo', escala: 2.3, tempo: 1.0, cor: '#ffd36b', tinta: 'fixa' }),
  golpe_da_serie: n({ nome: 'Golpe final da série', grupo: 'físico', impacto: 'golpe_da_serie', escala: 2.1, tempo: 1.0, cor: '#ff8a5c', tinta: 'fixa' }),
  golpe_que_cura: n({ nome: 'Golpe que cura', grupo: 'apoio', impacto: 'golpe_que_cura', escala: 1.9, tempo: 1.0, cor: '#7ee0a0', tinta: 'fixa' }),
  roubar_carga: n({ nome: 'Roubou Carga', grupo: 'energia', impacto: 'roubar_carga', escala: 1.8, tempo: 1.0, cor: '#a77bff', tinta: 'fixa' }),
  carga_roubada: n({ nome: 'Carga roubada', grupo: 'energia', impacto: 'carga_roubada', escala: 1.7, tempo: 1.0, cor: '#7d8cff', tinta: 'fixa' }),
  guarda_do_golpe: n({ nome: 'Guarda do golpe', grupo: 'apoio', impacto: 'guarda_do_golpe', escala: 1.8, tempo: 1.0, cor: '#7fc4ff', tinta: 'fixa' }),
  acelera: n({ nome: 'Acelerou', grupo: 'apoio', impacto: 'acelera', escala: 1.8, tempo: 1.0, cor: '#ffe066', tinta: 'fixa' }),
  // o ataque básico de cada personagem com animação e som próprios (tools/vfx/familias_v2/basicos_*.py)
  golpe_do_potencial: n({ nome: 'Golpe do potencial', grupo: 'físico', impacto: 'golpe_do_potencial', escala: 2.0, tempo: 1.0, cor: '#ffe066', tinta: 'fixa' }),
  braco_namekiano: n({ nome: 'Braço namekiano', grupo: 'físico', aponta: true, impacto: 'braco_namekiano', escala: 2.0, tempo: 1.0, cor: '#4cc35a', tinta: 'fixa' }),
  punho_lendario: n({ nome: 'Punho lendário', grupo: 'físico', impacto: 'punho_lendario', escala: 2.3, tempo: 1.0, cor: '#9cff3a', tinta: 'fixa' }),
  toque_da_destruicao: n({ nome: 'Toque da destruição', grupo: 'magia', impacto: 'toque_da_destruicao', escala: 1.9, tempo: 1.0, cor: '#b06cff', tinta: 'fixa' }),
  soco_casual: n({ nome: 'Soco casual', grupo: 'físico', impacto: 'soco_casual', escala: 2.4, tempo: 1.0, cor: '#e8c97a', tinta: 'fixa' }),
  punho_amaldicoado: n({ nome: 'Punho amaldiçoado', grupo: 'físico', impacto: 'punho_amaldicoado', escala: 2.0, tempo: 1.0, cor: '#ff3030', tinta: 'fixa' }),
  desmanche: n({ nome: 'Desmanche', grupo: 'corte', impacto: 'desmanche', escala: 2.0, tempo: 1.0, cor: '#ff5c8a', tinta: 'fixa' }),
  choque_do_pikachu: n({ nome: 'Choque', grupo: 'elemento', faixa: 'raio_faixa', pula: 0.1, impacto: 'choque_do_pikachu', escala: 1.9, tempo: 1.0, cor: '#ffd91a', tinta: 'fixa' }),
  soco_relampago: n({ nome: 'Soco relâmpago', grupo: 'físico', impacto: 'soco_relampago', escala: 2.0, tempo: 1.0, cor: '#ffb300', tinta: 'fixa' }),
  kusanagi: n({ nome: 'Corte da Kusanagi', grupo: 'corte', impacto: 'kusanagi', escala: 2.0, tempo: 1.0, cor: '#6f9cff', tinta: 'fixa' }),
  shuriken: n({ nome: 'Shuriken Uchiha', grupo: 'projétil', viagem: 'shuriken_voando', pula: 0.12, aponta: true, impacto: 'shuriken', escala: 1.8, tempo: 1.0, cor: '#ff3b3b', tinta: 'fixa' }),
  soco_de_chakra: n({ nome: 'Soco de chakra', grupo: 'físico', impacto: 'soco_de_chakra', escala: 2.2, tempo: 1.0, cor: '#ff7ac8', tinta: 'fixa' }),
  chute_demoniaco: n({ nome: 'Chute demoníaco', grupo: 'físico', impacto: 'chute_demoniaco', escala: 2.1, tempo: 1.0, cor: '#ff5a6e', tinta: 'fixa' }),
  saque_do_trovao: n({ nome: 'Saque do trovão', grupo: 'corte', aponta: true, impacto: 'saque_do_trovao', escala: 2.2, tempo: 1.0, cor: '#ffcc33', tinta: 'fixa' }),
  laminas_serrilhadas: n({ nome: 'Lâminas serrilhadas', grupo: 'corte', impacto: 'laminas_serrilhadas', escala: 2.0, tempo: 1.0, cor: '#7aa6d6', tinta: 'fixa' }),
  martelo_e_prego: n({ nome: 'Martelo e prego', grupo: 'projétil', viagem: 'facas_voando', pula: 0.1, aponta: true, impacto: 'martelo_e_prego', escala: 2.0, tempo: 1.0, cor: '#c070ff', tinta: 'fixa' }),
  kunai_de_hiraishin: n({ nome: 'Kunai de Hiraishin', grupo: 'projétil', aponta: true, impacto: 'kunai_de_hiraishin', escala: 1.9, tempo: 1.0, cor: '#ffe45a', tinta: 'fixa' }),
  leque_gunbai: n({ nome: 'Leque Gunbai', grupo: 'elemento', aponta: true, impacto: 'leque_gunbai', escala: 2.2, tempo: 1.0, cor: '#5f7bff', tinta: 'fixa' }),
  rinnegan: n({ nome: 'Golpe dos Seis Caminhos', grupo: 'energia', impacto: 'rinnegan', escala: 2.2, tempo: 1.0, cor: '#a678ff', tinta: 'fixa' }),
  laminas_odm: n({ nome: 'Corte das lâminas', grupo: 'corte', aponta: true, impacto: 'laminas_odm', escala: 2.0, tempo: 1.0, cor: '#66d9c0', tinta: 'fixa' }),
  soco_titanico: n({ nome: 'Soco titânico', grupo: 'físico', aponta: true, impacto: 'soco_titanico', escala: 2.3, tempo: 1.0, cor: '#ff7048', tinta: 'fixa' }),
  garras_de_killua: n({ nome: 'Garras de relâmpago', grupo: 'corte', impacto: 'garras_de_killua', escala: 2.0, tempo: 1.0, cor: '#7fe4ff', tinta: 'fixa' }),
  punho_transmutado: n({ nome: 'Punho transmutado', grupo: 'especial', impacto: 'punho_transmutado', escala: 2.1, tempo: 1.0, cor: '#5aa0ff', tinta: 'fixa' }),
  estalo_de_dedos: n({ nome: 'Estalo de dedos', grupo: 'elemento', aponta: true, impacto: 'estalo_de_dedos', escala: 2.2, tempo: 1.0, cor: '#ff7a30', tinta: 'fixa' }),
  matadora_de_dragoes: n({ nome: 'Matadora de Dragões', grupo: 'corte', impacto: 'matadora_de_dragoes', escala: 2.3, tempo: 1.0, cor: '#b9c0c8', tinta: 'fixa' }),
  soco_do_stand: n({ nome: 'Soco do Stand', grupo: 'físico', aponta: true, impacto: 'soco_do_stand', escala: 2.0, tempo: 1.0, cor: '#a07cff', tinta: 'fixa' }),
  soco_da_vida: n({ nome: 'Soco da vida', grupo: 'especial', impacto: 'soco_da_vida', escala: 2.0, tempo: 1.0, cor: '#ffd447', tinta: 'fixa' }),
  pancada_de_sangue: n({ nome: 'Pancada de sangue', grupo: 'físico', impacto: 'pancada_de_sangue', escala: 2.1, tempo: 1.0, cor: '#ff3d3d', tinta: 'fixa' }),
  dedo_apontado: n({ nome: 'Dedo apontado', grupo: 'especial', impacto: 'dedo_apontado', escala: 1.9, tempo: 1.0, cor: '#c8408a', tinta: 'fixa' }),
  feitico_comum: n({ nome: 'Zoltraak', grupo: 'magia', faixa: 'feixe', pula: 0.15, aponta: true, impacto: 'feitico_comum', escala: 2.2, tempo: 1.0, cor: '#7aa6ff', tinta: 'fixa' }),
  golpe_de_panico: n({ nome: 'Golpe de pânico', grupo: 'físico', impacto: 'golpe_de_panico', escala: 1.8, tempo: 1.0, cor: '#ff80c4', tinta: 'fixa' }),
  golpe_do_espiao: n({ nome: 'Golpe do espião', grupo: 'físico', impacto: 'golpe_do_espiao', escala: 1.9, tempo: 1.0, cor: '#6fe0a0', tinta: 'fixa' }),
  agulha_de_espinho: n({ nome: 'Agulha de espinho', grupo: 'corte', aponta: true, impacto: 'agulha_de_espinho', escala: 2.0, tempo: 1.0, cor: '#ff5c8a', tinta: 'fixa' }),
  adaga_de_kamish: n({ nome: 'Adaga de Kamish', grupo: 'corte', impacto: 'adaga_de_kamish', escala: 1.9, tempo: 1.0, cor: '#9b6bff', tinta: 'fixa' }),
  kagune: n({ nome: 'Kagune', grupo: 'físico', aponta: true, impacto: 'kagune', escala: 2.1, tempo: 1.0, cor: '#ff3b4e', tinta: 'fixa' }),
  carta_magica: n({ nome: 'Carta mágica', grupo: 'magia', impacto: 'carta_magica', escala: 2.0, tempo: 1.0, cor: '#c86bff', tinta: 'fixa' }),
  carta_dragao: n({ nome: 'Carta do dragão', grupo: 'energia', faixa: 'feixe_pesado', pula: 0.15, aponta: true, impacto: 'carta_dragao', escala: 2.2, tempo: 1.0, cor: '#6cb6ff', tinta: 'fixa' }),
  meteoros_de_pegaso: n({ nome: 'Meteoros de Pégaso', grupo: 'físico', aponta: true, impacto: 'meteoros_de_pegaso', escala: 2.0, tempo: 1.0, cor: '#4f9dff', tinta: 'fixa' }),
  punho_do_dragao: n({ nome: 'Punho do Dragão', grupo: 'físico', impacto: 'punho_do_dragao', escala: 2.1, tempo: 1.0, cor: '#3fe0c5', tinta: 'fixa' }),
  corrente_de_andromeda: n({ nome: 'Corrente de Andrômeda', grupo: 'projétil', aponta: true, impacto: 'corrente_de_andromeda', escala: 2.0, tempo: 1.0, cor: '#ff7ac0', tinta: 'fixa' }),
  rendicao: n({ nome: 'Rendição', grupo: 'magia', impacto: 'rendicao', escala: 2.0, tempo: 1.0, cor: '#ffc93c', tinta: 'fixa' }),
  tiara_lunar: n({ nome: 'Tiara lunar', grupo: 'projétil', viagem: 'tiara_voando', pula: 0.15, aponta: true, impacto: 'tiara_lunar', escala: 1.9, tempo: 1.0, cor: '#ffe27a', tinta: 'fixa' }),
  chama_do_triangulo: n({ nome: 'Chama do triângulo', grupo: 'magia', impacto: 'chama_do_triangulo', escala: 2.0, tempo: 1.0, cor: '#59c8ff', tinta: 'fixa' }),
  batarangue: n({ nome: 'Batarangue', grupo: 'projétil', viagem: 'batarangue_voando', pula: 0.15, aponta: true, impacto: 'batarangue', escala: 2.0, tempo: 1.0, cor: '#7d9cc4', tinta: 'fixa' }),
  soco_de_aco: n({ nome: 'Soco de aço', grupo: 'físico', aponta: true, impacto: 'soco_de_aco', escala: 2.2, tempo: 1.0, cor: '#4a8cff', tinta: 'fixa' }),
  teia_e_soco: n({ nome: 'Teia e soco', grupo: 'físico', aponta: true, impacto: 'teia_e_soco', escala: 2.0, tempo: 1.0, cor: '#ff4a4a', tinta: 'fixa' }),
  disparo_arcano: n({ nome: 'Disparo arcano', grupo: 'magia', viagem: 'orbe', aponta: true, impacto: 'disparo_arcano', escala: 2.0, tempo: 1.0, cor: '#ffa640', tinta: 'fixa' }),
  bracelete: n({ nome: 'Golpe de bracelete', grupo: 'físico', aponta: true, impacto: 'bracelete', escala: 2.0, tempo: 1.0, cor: '#f5c542', tinta: 'fixa' }),
  repulsor: n({ nome: 'Repulsor', grupo: 'energia', faixa: 'feixe', pula: 0.15, aponta: true, impacto: 'repulsor', escala: 2.0, tempo: 1.0, cor: '#7fd8ff', tinta: 'fixa' }),
  escudo_do_capitao: n({ nome: 'Escudo arremessado', grupo: 'projétil', viagem: 'escudo_voando', pula: 0.15, aponta: true, impacto: 'escudo_do_capitao', escala: 2.0, tempo: 1.0, cor: '#5a86ff', tinta: 'fixa' }),
  corvo_da_alma: n({ nome: 'Corvo da alma', grupo: 'magia', viagem: 'corvo_voando', pula: 0.1, impacto: 'corvo_da_alma', escala: 2.2, tempo: 1.0, cor: '#9c6bff', tinta: 'fixa' }),
  manopla: n({ nome: 'Manopla', grupo: 'físico', aponta: true, impacto: 'manopla', escala: 2.2, tempo: 1.0, cor: '#f0a93c', tinta: 'fixa' }),
  magia_do_caos: n({ nome: 'Magia do caos', grupo: 'magia', impacto: 'magia_do_caos', escala: 2.0, tempo: 1.0, cor: '#ff3d6e', tinta: 'fixa' }),
  soco_de_pym: n({ nome: 'Soco de Pym', grupo: 'físico', aponta: true, impacto: 'soco_de_pym', escala: 2.0, tempo: 1.0, cor: '#ff5f57', tinta: 'fixa' }),
  punho_fotonico: n({ nome: 'Punho fotônico', grupo: 'energia', aponta: true, impacto: 'punho_fotonico', escala: 2.2, tempo: 1.0, cor: '#ffe066', tinta: 'fixa' }),
  corrente_flamejante: n({ nome: 'Corrente flamejante', grupo: 'elemento', aponta: true, impacto: 'corrente_flamejante', escala: 2.2, tempo: 1.0, cor: '#ff7a2a', tinta: 'fixa' }),
  toque_absorvente: n({ nome: 'Toque absorvente', grupo: 'especial', aponta: true, impacto: 'toque_absorvente', escala: 1.9, tempo: 1.0, cor: '#8fdc4a', tinta: 'fixa' }),
  golpe_psiquico: n({ nome: 'Golpe psíquico', grupo: 'energia', impacto: 'golpe_psiquico', escala: 2.0, tempo: 1.0, cor: '#e070ff', tinta: 'fixa' }),
  tentaculo_simbionte: n({ nome: 'Tentáculo simbionte', grupo: 'físico', aponta: true, impacto: 'tentaculo_simbionte', escala: 2.0, tempo: 1.0, cor: '#9aa3d6', tinta: 'fixa' }),
  lamina_viva: n({ nome: 'Lâmina viva', grupo: 'corte', impacto: 'lamina_viva', escala: 2.0, tempo: 1.0, cor: '#e8303c', tinta: 'fixa' }),
  adaga_ilusoria: n({ nome: 'Adaga ilusória', grupo: 'corte', aponta: true, impacto: 'adaga_ilusoria', escala: 2.0, tempo: 1.0, cor: '#3fd16a', tinta: 'fixa' }),
  toque_do_devorador: n({ nome: 'Toque do Devorador', grupo: 'energia', impacto: 'toque_do_devorador', escala: 2.4, tempo: 1.0, cor: '#7d7bff', tinta: 'fixa' }),
  blasters_elementais: n({ nome: 'Blasters elementais', grupo: 'projétil', viagem: 'tiro', pula: 0.1, aponta: true, impacto: 'blasters_elementais', escala: 1.9, tempo: 1.0, cor: '#ff8a3d', tinta: 'fixa' }),
  arma_grande: n({ nome: 'Arma grande', grupo: 'projétil', aponta: true, impacto: 'arma_grande', escala: 2.1, tempo: 1.0, cor: '#ffcf3f', tinta: 'fixa' }),
  tridente: n({ nome: 'Golpe do tridente', grupo: 'físico', aponta: true, impacto: 'tridente', escala: 2.0, tempo: 1.0, cor: '#33c6d6', tinta: 'fixa' }),
  canhao_sonico: n({ nome: 'Canhão sônico', grupo: 'energia', faixa: 'feixe', pula: 0.15, aponta: true, impacto: 'canhao_sonico', escala: 1.9, tempo: 1.0, cor: '#5aa8ff', tinta: 'fixa' }),
  garras_cineticas: n({ nome: 'Garras cinéticas', grupo: 'corte', impacto: 'garras_cineticas', escala: 2.0, tempo: 1.0, cor: '#a855ff', tinta: 'fixa' }),
  punho_de_apokolips: n({ nome: 'Punho de Apokolips', grupo: 'físico', aponta: true, impacto: 'punho_de_apokolips', escala: 2.1, tempo: 1.0, cor: '#ff4a2a', tinta: 'fixa' }),
  mao_da_perdicao: n({ nome: 'Mão da Perdição', grupo: 'físico', impacto: 'mao_da_perdicao', escala: 2.2, tempo: 1.0, cor: '#d9894a', tinta: 'fixa' }),
  masamune: n({ nome: 'Golpe da Masamune', grupo: 'corte', impacto: 'masamune', escala: 2.4, tempo: 1.0, cor: '#8fb6e0', tinta: 'fixa' }),
  laminas_do_caos: n({ nome: 'Lâminas do Caos', grupo: 'corte', impacto: 'laminas_do_caos', escala: 2.2, tempo: 1.0, cor: '#ff6a1f', tinta: 'fixa' }),
  espada_mestra: n({ nome: 'Espada Mestra', grupo: 'corte', impacto: 'espada_mestra', escala: 2.0, tempo: 1.0, cor: '#6fd6ff', tinta: 'fixa' }),
  canhao_de_braco: n({ nome: 'Canhão de braço', grupo: 'projétil', viagem: 'bola_ki', pula: 0.15, aponta: true, impacto: 'canhao_de_braco', escala: 1.9, tempo: 1.0, cor: '#ff8a1c', tinta: 'fixa' }),
  rebellion_e_ebony: n({ nome: 'Rebellion e Ebony', grupo: 'corte', impacto: 'rebellion_e_ebony', escala: 2.1, tempo: 1.0, cor: '#e8303c', tinta: 'fixa' }),
  corte_dimensional: n({ nome: 'Corte dimensional', grupo: 'corte', impacto: 'corte_dimensional', escala: 2.0, tempo: 1.0, cor: '#4f86ff', tinta: 'fixa' }),
  cqc: n({ nome: 'CQC', grupo: 'físico', impacto: 'cqc', escala: 2.0, tempo: 1.0, cor: '#b7b25e', tinta: 'fixa' }),
  golpe_sobre_humano: n({ nome: 'Golpe sobre-humano', grupo: 'físico', impacto: 'golpe_sobre_humano', escala: 2.0, tempo: 1.0, cor: '#ff3f2e', tinta: 'fixa' }),
  duas_pistolas: n({ nome: 'Duas pistolas', grupo: 'projétil', viagem: 'tiro', aponta: true, impacto: 'duas_pistolas', escala: 2.0, tempo: 1.0, cor: '#3cc6b4', tinta: 'fixa' }),
  lamina_oculta: n({ nome: 'Lâmina oculta', grupo: 'corte', aponta: true, impacto: 'lamina_oculta', escala: 1.9, tempo: 1.0, cor: '#e8c24a', tinta: 'fixa' }),
  spin_attack: n({ nome: 'Spin Attack', grupo: 'físico', impacto: 'spin_attack', escala: 2.0, tempo: 1.0, cor: '#2f6dff', tinta: 'fixa' }),
  z_saber: n({ nome: 'Corte do Z-Saber', grupo: 'corte', impacto: 'z_saber', escala: 2.1, tempo: 1.0, cor: '#3dff7d', tinta: 'fixa' }),
  pisada_do_mario: n({ nome: 'Pisada do Mario', grupo: 'físico', impacto: 'pisada_do_mario', escala: 2.0, tempo: 1.0, cor: '#ff3b3b', tinta: 'fixa' }),
  chute_relampago: n({ nome: 'Chute relâmpago', grupo: 'físico', aponta: true, impacto: 'chute_relampago', escala: 2.1, tempo: 1.0, cor: '#4f8dff', tinta: 'fixa' }),
  kunai_do_inferno: n({ nome: 'Kunai do inferno', grupo: 'projétil', viagem: 'facas_voando', pula: 0.1, aponta: true, impacto: 'kunai_do_inferno', escala: 2.1, tempo: 1.0, cor: '#ffa526', tinta: 'fixa' }),
  chute_do_dragao: n({ nome: 'Chute do dragão', grupo: 'físico', aponta: true, impacto: 'chute_do_dragao', escala: 2.1, tempo: 1.0, cor: '#ff5a1f', tinta: 'fixa' }),
  soco_do_diabo: n({ nome: 'Soco do Diabo', grupo: 'físico', aponta: true, impacto: 'soco_do_diabo', escala: 2.0, tempo: 1.0, cor: '#a35cff', tinta: 'fixa' }),
  keyblade: n({ nome: 'Chave-espada', grupo: 'corte', impacto: 'keyblade', escala: 2.0, tempo: 1.0, cor: '#ffd23f', tinta: 'fixa' }),
  aparar_e_cortar: n({ nome: 'Aparar e cortar', grupo: 'corte', impacto: 'aparar_e_cortar', escala: 2.0, tempo: 1.0, cor: '#ffae42', tinta: 'fixa' }),
  lamina_protetica: n({ nome: 'Lâmina protética', grupo: 'corte', impacto: 'lamina_protetica', escala: 2.0, tempo: 1.0, cor: '#ff3b5c', tinta: 'fixa' }),
  frostmourne: n({ nome: 'Frostmourne', grupo: 'corte', impacto: 'frostmourne', escala: 2.1, tempo: 1.0, cor: '#6cc8ff', tinta: 'fixa' }),
  cortador_de_plasma: n({ nome: 'Cortador de plasma', grupo: 'projétil', viagem: 'tiro', pula: 0.15, aponta: true, impacto: 'cortador_de_plasma', escala: 2.0, tempo: 1.0, cor: '#59c9ff', tinta: 'fixa' }),
  arma_da_gravidade: n({ nome: 'Arma da gravidade', grupo: 'projétil', aponta: true, impacto: 'arma_da_gravidade', escala: 2.1, tempo: 1.0, cor: '#ff9a2e', tinta: 'fixa' }),
  grande_faca: n({ nome: 'Grande Faca', grupo: 'corte', impacto: 'grande_faca', escala: 2.3, tempo: 1.0, cor: '#d0703a', tinta: 'fixa' }),
  adaga_do_tempo: n({ nome: 'Adaga do tempo', grupo: 'corte', impacto: 'adaga_do_tempo', escala: 2.0, tempo: 1.0, cor: '#f2c14e', tinta: 'fixa' }),
  espada_de_alucard: n({ nome: 'Espada de Alucard', grupo: 'corte', impacto: 'espada_de_alucard', escala: 2.0, tempo: 1.0, cor: '#9d7bff', tinta: 'fixa' }),
  sais: n({ nome: 'Sais', grupo: 'corte', aponta: true, impacto: 'sais', escala: 2.0, tempo: 1.0, cor: '#e8463c', tinta: 'fixa' }),
  nunchakus: n({ nome: 'Nunchakus', grupo: 'físico', aponta: true, impacto: 'nunchakus', escala: 2.0, tempo: 1.0, cor: '#ff8c2a', tinta: 'fixa' }),
  bicada: n({ nome: 'Bicada', grupo: 'físico', aponta: true, impacto: 'bicada', escala: 1.9, tempo: 1.0, cor: '#f0503c', tinta: 'fixa' }),
  golpe_alienigena: n({ nome: 'Golpe alienígena', grupo: 'físico', aponta: true, impacto: 'golpe_alienigena', escala: 2.1, tempo: 1.0, cor: '#5ef05a', tinta: 'fixa' }),
  soco_de_marinheiro: n({ nome: 'Soco de marinheiro', grupo: 'físico', aponta: true, impacto: 'soco_de_marinheiro', escala: 2.1, tempo: 1.0, cor: '#5aa0f0', tinta: 'fixa' }),
  machado_de_energon: n({ nome: 'Machado de energon', grupo: 'corte', aponta: true, impacto: 'machado_de_energon', escala: 2.2, tempo: 1.0, cor: '#ff9a30', tinta: 'fixa' }),
  karate: n({ nome: 'Karatê', grupo: 'físico', impacto: 'karate', escala: 1.9, tempo: 1.0, cor: '#f5dc3c', tinta: 'fixa' }),
  laco: n({ nome: 'Laço', grupo: 'especial', aponta: true, impacto: 'laco', escala: 2.1, tempo: 1.0, cor: '#e0b060', tinta: 'fixa' }),
  fogo_azul: n({ nome: 'Fogo azul', grupo: 'elemento', aponta: true, impacto: 'fogo_azul', escala: 2.1, tempo: 1.0, cor: '#3c9cff', tinta: 'fixa' }),
  bigorna: n({ nome: 'Bigorna ACME', grupo: 'especial', impacto: 'bigorna', escala: 2.1, tempo: 1.0, cor: '#d88a4a', tinta: 'fixa' }),
  frigideira: n({ nome: 'Frigideira', grupo: 'físico', aponta: true, impacto: 'frigideira', escala: 2.0, tempo: 1.0, cor: '#8fa8c8', tinta: 'fixa' }),
  cajado_da_caveira: n({ nome: 'Cajado da Caveira', grupo: 'magia', aponta: true, impacto: 'cajado_da_caveira', escala: 2.1, tempo: 1.0, cor: '#a060e0', tinta: 'fixa' }),
  espada_de_augurio: n({ nome: 'Espada de Augúrio', grupo: 'corte', aponta: true, impacto: 'espada_de_augurio', escala: 2.2, tempo: 1.0, cor: '#ff5040', tinta: 'fixa' }),
  barrigada: n({ nome: 'Barrigada', grupo: 'físico', impacto: 'barrigada', escala: 2.2, tempo: 1.0, cor: '#ffd90f', tinta: 'fixa' }),
  estilingue: n({ nome: 'Estilingue', grupo: 'projétil', viagem: 'rocha', pula: 0.15, impacto: 'estilingue', escala: 2.0, tempo: 1.0, cor: '#ff7a1a', tinta: 'fixa' }),
  gadget_surpresa: n({ nome: 'Gadget surpresa', grupo: 'físico', aponta: true, impacto: 'gadget_surpresa', escala: 2.1, tempo: 1.0, cor: '#ff5a4a', tinta: 'fixa' }),
  raio_fantasma: n({ nome: 'Raio fantasma', grupo: 'energia', aponta: true, impacto: 'raio_fantasma', escala: 2.1, tempo: 1.0, cor: '#5cff8a', tinta: 'fixa' }),
  flor_de_lapela: n({ nome: 'Flor de lapela', grupo: 'elemento', impacto: 'flor_de_lapela', escala: 2.0, tempo: 1.0, cor: '#a8ff3e', tinta: 'fixa' }),
  taco_de_beisebol: n({ nome: 'Taco de beisebol', grupo: 'físico', impacto: 'taco_de_beisebol', escala: 2.1, tempo: 1.0, cor: '#ff5fa8', tinta: 'fixa' }),
  raio_de_gaia: n({ nome: 'Raio de Gaia', grupo: 'energia', faixa: 'feixe', pula: 0.15, aponta: true, impacto: 'raio_de_gaia', escala: 2.2, tempo: 1.0, cor: '#3fc6ff', tinta: 'fixa' }),
  mordida_cartoon: n({ nome: 'Mordida medrosa', grupo: 'físico', impacto: 'mordida_cartoon', escala: 2.0, tempo: 1.0, cor: '#c98a3a', tinta: 'fixa' }),
  dardo_crescente: n({ nome: 'Dardos crescentes', grupo: 'projétil', viagem: 'dardo_voando', pula: 0.15, aponta: true, impacto: 'dardo_crescente', escala: 2.0, tempo: 1.0, cor: '#9fb4dc', tinta: 'fixa' }),
  // o básico de quem só dá um soco ou um chute, na cor do personagem
  soco_basico: n({ nome: 'Soco', grupo: 'físico', aponta: true, impacto: 'soco_basico', escala: 1.8, tempo: 1.0, tinta: 'personagem' }),
  chute_basico: n({ nome: 'Chute', grupo: 'físico', aponta: true, impacto: 'chute_basico', escala: 1.85, tempo: 1.0, tinta: 'personagem' }),
  // as três técnicas do Madara (tools/vfx/familias_v2/madara.py)
  susanoo_perfeito: n({ nome: 'Susanoo Perfeito', grupo: 'especial', impacto: 'susanoo_perfeito', preparo: 'susanoo_manto', noAtor: 'susanoo_manto', escala: 2.4, tempo: 1.0, cor: '#6f7fff', tinta: 'fixa' }),
  meteoro_madara: n({ nome: 'Meteoro', grupo: 'elemento', impacto: 'meteoro_madara', noCentro: true, escala: 2.5, tempo: 1.0, cor: '#ff8a3a', tinta: 'fixa' }),
  // Kakashi, Yusuke e Killua: as três de cada um, desenhadas para eles (tools/vfx/familias_v2/ninjas_e_detetives.py)
  sharingan_kakashi: n({ nome: 'Sharingan', grupo: 'magia', impacto: 'sharingan_kakashi', noAtor: 'sharingan_ator', escala: 2.3, tempo: 1.0, cor: '#ff3b4a', tinta: 'fixa' }),
  raikiri: n({ nome: 'Raikiri', grupo: 'elemento', preparo: 'raikiri_mao', impacto: 'raikiri_impacto', aponta: true, escala: 2.3, tempo: 1.0, cor: '#6fc0ff', tinta: 'fixa' }),
  kamui: n({ nome: 'Kamui', grupo: 'magia', impacto: 'kamui', noAtor: 'sharingan_ator', escala: 2.4, tempo: 1.0, cor: '#a06bff', tinta: 'fixa' }),
  soco_espiritual: n({ nome: 'Soco espiritual', grupo: 'físico', impacto: 'soco_espiritual', aponta: true, escala: 2.3, tempo: 1.0, cor: '#5fb4ff', tinta: 'fixa' }),
  reigun: n({ nome: 'Reigun', grupo: 'projétil', preparo: 'reigun_carga', viagem: 'reigun_bala', impacto: 'reigun_explosao', escala: 2.4, tempo: 1.0, cor: '#4fa8ff', tinta: 'fixa' }),
  rei_shotgun: n({ nome: 'Shotgun', grupo: 'projétil', viagem: 'shotgun_rajada', impacto: 'shotgun_impacto', escala: 2.3, tempo: 1.0, cor: '#4fa8ff', tinta: 'fixa' }),
  ritmo_eletrico: n({ nome: 'Ritmo elétrico', grupo: 'físico', impacto: 'ritmo_eletrico', escala: 2.3, tempo: 1.0, cor: '#5fb8ff', tinta: 'fixa' }),
  palma_relampago: n({ nome: 'Palma relâmpago', grupo: 'elemento', faixa: 'palma_faixa', impacto: 'palma_impacto', escala: 2.2, tempo: 1.0, cor: '#5fb8ff', tinta: 'fixa' }),
  velocidade_divina: n({ nome: 'Velocidade divina', grupo: 'físico', impacto: 'velocidade_divina', noAtor: 'velocidade_aura', escala: 2.4, tempo: 1.0, cor: '#5fb8ff', tinta: 'fixa' }),
  // Cloud e Donkey Kong: as três de cada um (tools/vfx/familias_v2/cloud_e_dk.py)
  golpe_ascendente: n({ nome: 'Golpe ascendente', grupo: 'corte', impacto: 'golpe_ascendente', escala: 2.4, tempo: 1.0, cor: '#7fd4ff', tinta: 'fixa' }),
  postura_de_guarda: n({ nome: 'Postura de guarda', grupo: 'corte', impacto: 'contra_buster', noAtor: 'guarda_buster', aponta: true, escala: 2.3, tempo: 1.0, cor: '#7fd4ff', tinta: 'fixa' }),
  omnislash: n({ nome: 'Omnislash', grupo: 'corte', preparo: 'limite_cloud', impacto: 'omnislash', escala: 2.5, tempo: 1.0, cor: '#6fd8c8', tinta: 'fixa' }),
  soco_giratorio: n({ nome: 'Soco giratório', grupo: 'físico', impacto: 'soco_giratorio', aponta: true, escala: 2.4, tempo: 1.0, cor: '#d89a5a', tinta: 'fixa' }),
  barril_arremessado: n({ nome: 'Barril arremessado', grupo: 'projétil', viagem: 'barril_voando', pula: 0.12, impacto: 'barril_quebrando', escala: 2.3, tempo: 1.0, cor: '#c8843f', tinta: 'fixa' }),
  batida_do_gorila: n({ nome: 'Batida do gorila', grupo: 'físico', preparo: 'batida_preparo', impacto: 'batida_do_gorila', noCentro: true, escala: 2.5, tempo: 1.0, cor: '#c8a070', tinta: 'fixa' }),
  // Naruto, Ikki e Luffy: as três de cada um (tools/vfx/familias_v2/naruto_ikki_luffy.py)
  clones_naruto: n({ nome: 'Clones das sombras', grupo: 'magia', impacto: 'clones_naruto', escala: 2.4, tempo: 1.0, cor: '#ff9a3c', tinta: 'fixa' }),
  rasengan: n({ nome: 'Rasengan', grupo: 'energia', preparo: 'rasengan_mao', impacto: 'rasengan_impacto', aponta: true, escala: 2.3, tempo: 1.0, cor: '#5fb4ff', tinta: 'fixa' }),
  modo_kurama: n({ nome: 'Manto da Kurama', grupo: 'especial', impacto: 'modo_kurama', escala: 2.4, tempo: 1.0, cor: '#ff8a2a', tinta: 'fixa' }),
  ave_fenix: n({ nome: 'Ave Fênix', grupo: 'projétil', viagem: 'fenix_voando', impacto: 'fenix_explosao', escala: 2.4, tempo: 1.0, cor: '#ff7a2e', tinta: 'fixa' }),
  golpe_fantasma: n({ nome: 'Golpe Fantasma', grupo: 'magia', impacto: 'golpe_fantasma', escala: 2.2, tempo: 1.0, cor: '#b07aff', tinta: 'fixa' }),
  renascimento: n({ nome: 'Renascimento', grupo: 'elemento', impacto: 'renascimento_chamas', noAtor: 'fenix_asas', escala: 2.5, tempo: 1.0, cor: '#ff6a2a', tinta: 'fixa' }),
  gomu_gatling: n({ nome: 'Gomu Gomu no Gatling', grupo: 'físico', impacto: 'gomu_gatling', aponta: true, escala: 2.4, tempo: 1.0, cor: '#ff5a4a', tinta: 'fixa' }),
  corpo_de_borracha: n({ nome: 'Corpo de borracha', grupo: 'especial', impacto: 'corpo_de_borracha', escala: 2.2, tempo: 1.0, cor: '#ff8a7a', tinta: 'fixa' }),
  gear_fifth_nika: n({ nome: 'Gear Fifth', grupo: 'especial', impacto: 'gear_fifth_nika', escala: 2.5, tempo: 1.0, cor: '#8090ff', tinta: 'fixa' }),
  // Toph (com o básico dela) e Gon (tools/vfx/familias_v2/toph_e_gon.py)
  pedra_da_toph: n({ nome: 'Pedra arremessada', grupo: 'projétil', viagem: 'pedra_bloco', impacto: 'pedra_estilhaca', noAtor: 'pisada_toph', escala: 2.2, tempo: 1.0, cor: '#c09a6a', tinta: 'fixa' }),
  visao_sismica: n({ nome: 'Visão sísmica', grupo: 'elemento', impacto: 'visao_sismica', noAtor: 'pisada_toph', escala: 2.3, tempo: 1.0, cor: '#c09a6a', tinta: 'fixa' }),
  muralha_de_terra: n({ nome: 'Muralha de terra', grupo: 'elemento', impacto: 'muralha_de_terra', noAtor: 'pisada_toph', escala: 2.4, tempo: 1.0, cor: '#c09a6a', tinta: 'fixa' }),
  metal_dobrado: n({ nome: 'Metal dobrado', grupo: 'elemento', preparo: 'metal_preparo', impacto: 'metal_dobrado', escala: 2.3, tempo: 1.0, cor: '#a8b8c8', tinta: 'fixa' }),
  jajanken_pedra: n({ nome: 'Jajanken: Pedra', grupo: 'físico', preparo: 'nen_gon', impacto: 'jajanken_pedra', aponta: true, escala: 2.4, tempo: 1.0, cor: '#ffd23f', tinta: 'fixa' }),
  jajanken_tesoura: n({ nome: 'Jajanken: Tesoura', grupo: 'corte', impacto: 'jajanken_tesoura', escala: 2.3, tempo: 1.0, cor: '#ffd23f', tinta: 'fixa' }),
  jajanken_papel: n({ nome: 'Jajanken: Papel', grupo: 'projétil', preparo: 'nen_gon', viagem: 'papel_bola', impacto: 'jajanken_papel', escala: 2.4, tempo: 1.0, cor: '#ffd23f', tinta: 'fixa' }),
  colera_do_dragao: n({ nome: 'Cólera do Dragão', grupo: 'elemento', atravessa: 'dragao_faixa', aponta: true, impacto: 'colera_impacto', escala: 2.4, tempo: 1.0, cor: '#5fe0c0', tinta: 'fixa' }),
  makankosappo: n({ nome: 'Makankosappo', grupo: 'energia', preparo: 'makanko_carga', faixa: 'makanko_faixa', aponta: true, impacto: 'makankosappo', escala: 2.3, tempo: 1.0, cor: '#ffd84a', tinta: 'fixa' }),
  escudo_do_mentor: n({ nome: 'Escudo do mentor', grupo: 'apoio', impacto: 'escudo_do_mentor', escala: 2.3, tempo: 1.0, cor: '#7dff8a', tinta: 'fixa' }),
  regeneracao_namekiana: n({ nome: 'Regeneração namekiana', grupo: 'apoio', impacto: 'regeneracao_namekiana', escala: 2.3, tempo: 1.0, cor: '#6dff7a', tinta: 'fixa' }),
  lanca_chamas: n({ nome: 'Lança-chamas', grupo: 'elemento', faixa: 'chamas_faixa', impacto: 'lanca_chamas_impacto', escala: 2.2, tempo: 1.0, cor: '#ff7a2e', tinta: 'fixa' }),
  garra_de_dragao: n({ nome: 'Garra de dragão', grupo: 'corte', impacto: 'garra_de_dragao', aponta: true, escala: 2.3, tempo: 1.0, cor: '#ff8a4a', tinta: 'fixa' }),
  explosao_de_fogo: n({ nome: 'Explosão de fogo', grupo: 'projétil', preparo: 'fogo_no_peito', viagem: 'bola_do_charizard', impacto: 'explosao_de_fogo', escala: 2.5, tempo: 1.0, cor: '#ff6a2a', tinta: 'fixa' }),
  tiro_do_buster: n({ nome: 'Mega Buster', grupo: 'projétil', viagem: 'buster_bala', impacto: 'buster_impacto', escala: 2.1, tempo: 1.0, cor: '#9fe0ff', tinta: 'fixa' }),
  arma_adquirida: n({ nome: 'Arma adquirida', grupo: 'projétil', noAtor: 'troca_de_arma', viagem: 'raio_copiado', impacto: 'raio_copiado_impacto', escala: 2.2, tempo: 1.0, cor: '#ffe14a', tinta: 'fixa' }),
  carga_maxima: n({ nome: 'Carga máxima', grupo: 'projétil', preparo: 'buster_carga', viagem: 'carga_maxima_bala', impacto: 'carga_maxima_impacto', escala: 2.4, tempo: 1.0, cor: '#7fd8ff', tinta: 'fixa' }),
  visao_de_calor: n({ nome: 'Visão de calor', grupo: 'energia', preparo: 'olhos_brilhando', faixa: 'calor_faixa', aponta: true, impacto: 'calor_impacto', escala: 2.2, tempo: 1.0, cor: '#ff4a3a', tinta: 'fixa' }),
  eu_te_seguro: n({ nome: 'Eu te seguro', grupo: 'apoio', impacto: 'eu_te_seguro', escala: 2.3, tempo: 1.0, cor: '#8edeff', tinta: 'fixa' }),
  ultimo_filho_de_krypton: n({ nome: 'Último filho de Krypton', grupo: 'físico', preparo: 'krypton_carga', impacto: 'ultimo_filho', noCentro: true, aponta: true, escala: 2.5, tempo: 1.0, cor: '#ffe08a', tinta: 'fixa' }),
  poeira_de_diamante: n({ nome: 'Pó de Diamante', grupo: 'elemento', faixa: 'diamante_faixa', aponta: true, impacto: 'diamante_impacto', escala: 2.2, tempo: 1.0, cor: '#9fe6ff', tinta: 'fixa' }),
  execucao_aurora: n({ nome: 'Execução Aurora', grupo: 'elemento', preparo: 'aurora_preparo', faixa: 'aurora_faixa', impacto: 'execucao_aurora', escala: 2.4, tempo: 1.0, cor: '#8ff0ff', tinta: 'fixa' }),
  zero_absoluto: n({ nome: 'Zero Absoluto', grupo: 'elemento', preparo: 'zero_preparo', impacto: 'zero_absoluto', noCentro: true, escala: 2.6, tempo: 1.0, cor: '#bff4ff', tinta: 'fixa' }),
  soco_do_hulk: n({ nome: 'Soco do Hulk', grupo: 'físico', impacto: 'soco_do_hulk', aponta: true, escala: 2.3, tempo: 1.0, cor: '#8fdc5a', tinta: 'fixa' }),
  hulk_esmaga: n({ nome: 'Hulk esmaga', grupo: 'físico', impacto: 'hulk_esmaga', escala: 2.5, tempo: 1.0, cor: '#8fdc5a', tinta: 'fixa' }),
  rugido_do_hulk: n({ nome: 'Rugido do Hulk', grupo: 'especial', impacto: 'rugido_do_hulk', noAtor: 'grito_hulk', aponta: true, escala: 2.3, tempo: 1.0, cor: '#a6e86a', tinta: 'fixa' }),
  mais_forte_ainda: n({ nome: 'Mais forte ainda', grupo: 'físico', impacto: 'mais_forte_ainda', noAtor: 'furia_hulk', escala: 2.4, tempo: 1.0, cor: '#7fdc5a', tinta: 'fixa' }),
  relampago_de_plasma: n({ nome: 'Relâmpago de Plasma', grupo: 'elemento', faixa: 'plasma_faixa', aponta: true, impacto: 'relampago_de_plasma', escala: 2.2, tempo: 1.0, cor: '#ffd84a', tinta: 'fixa' }),
  velocidade_da_luz: n({ nome: 'Velocidade da Luz', grupo: 'elemento', impacto: 'velocidade_da_luz', noCentro: true, escala: 2.5, tempo: 1.0, cor: '#ffe066', tinta: 'fixa' }),
  rugido_do_leao: n({ nome: 'Rugido do Leão', grupo: 'projétil', preparo: 'cosmo_leao', viagem: 'leao_dourado', impacto: 'rugido_do_leao', escala: 2.5, tempo: 1.0, cor: '#ffc83a', tinta: 'fixa' }),
  ceifadora_de_almas: n({ nome: 'Ceifadora de Almas', grupo: 'corte', impacto: 'ceifadora_de_almas', aponta: true, escala: 2.4, tempo: 1.0, cor: '#8fd4ff', tinta: 'fixa' }),
  erguer_os_mortos: n({ nome: 'Erguer os mortos', grupo: 'apoio', impacto: 'erguer_os_mortos', escala: 2.4, tempo: 1.0, cor: '#9fe0d0', tinta: 'fixa' }),
  praga_da_carne: n({ nome: 'Praga da Carne', grupo: 'magia', preparo: 'runa_lich', impacto: 'praga_da_carne', noCentro: true, escala: 2.6, tempo: 1.0, cor: '#9fe0b8', tinta: 'fixa' }),
  rajada_do_aang: n({ nome: 'Rajada de ar', grupo: 'projétil', viagem: 'bola_de_ar', impacto: 'rajada_aang', escala: 2.2, tempo: 1.0, cor: '#7fd0ff', tinta: 'fixa' }),
  dobra_de_agua: n({ nome: 'Dobra de água', grupo: 'apoio', impacto: 'dobra_de_agua', escala: 2.3, tempo: 1.0, cor: '#5fb8ff', tinta: 'fixa' }),
  estado_avatar_aang: n({ nome: 'Estado Avatar', grupo: 'elemento', preparo: 'avatar_brilho', impacto: 'avatar_aang', noCentro: true, escala: 2.6, tempo: 1.0, cor: '#7fd0ff', tinta: 'fixa' }),
  controle_de_chakra: n({ nome: 'Controle de chakra', grupo: 'apoio', impacto: 'controle_de_chakra', escala: 2.2, tempo: 1.0, cor: '#6fe0b0', tinta: 'fixa' }),
  forca_monstruosa: n({ nome: 'Força monstruosa', grupo: 'físico', impacto: 'forca_monstruosa', aponta: true, escala: 2.4, tempo: 1.0, cor: '#ff7aae', tinta: 'fixa' }),
  byakugou: n({ nome: 'Byakugou', grupo: 'apoio', preparo: 'byakugou_selo', impacto: 'byakugou_cura', escala: 2.3, tempo: 1.0, cor: '#6fe8a0', tinta: 'fixa' }),
  mugen_tsukuyomi: n({ nome: 'Mugen Tsukuyomi', grupo: 'especial', impacto: 'mugen_tsukuyomi', noCentro: true, escala: 2.6, tempo: 1.0, cor: '#ff4a5a', tinta: 'fixa' }),
} as const satisfies Record<string, Familia>;

export type FamiliaNova = keyof typeof FAMILIAS_NOVAS;

/** O som próprio de cada família nova (nome do arquivo em public/assets/audio/sfx). */
export const SOM_DA_NOVA = (k: FamiliaNova): string => (k === 'transformacao' ? 'transformacao-v2' : k.replace(/_/g, '-'));

/** Estas acontecem no alvo, sem nada voando até ele. */
export const NOVAS_NO_ALVO = new Set<FamiliaNova>(['ressurreicao', 'renascer', 'brasas_renascendo', 'provocar', 'copia', 'esquiva', 'ultima_resistencia', 'sono', 'cegueira', 'dissipar', 'reflexo', 'espinhos', 'vampirismo', 'olho', 'hipnose', 'relogio', 'runas', 'sarcofago', 'encanto', 'caveira', 'clones',
  'teleporte', 'fenda', 'sorte', 'confusao', 'pentagrama', 'invocacao', 'lua_vermelha', 'susanoo', 'dominio', 'desintegrar', 'buraco_negro',
  'gravidade', 'cosmico', 'tempestade', 'raio_divino', 'chuva_de_meteoros', 'lua', 'marca', 'silencio', 'medo', 'exposto', 'lentidao', 'enfraquecimento',
  'inv_cao', 'inv_sombras', 'inv_mago', 'inv_dragao', 'inv_gomorrah', 'inv_ora', 'inv_feras', 'inv_vassouras', 'inv_clones', 'inv_androide',
  'death_note', 'shoryuken', 'punho_divergente', 'agua_benta', 'kaioken', 'instinto', 'shun_goku_satsu', 'spin_dash',
  'estado_avatar', 'tenho_a_forca', 'muda',
  'quique', 'golpe_largo', 'golpe_da_serie', 'golpe_que_cura', 'roubar_carga', 'carga_roubada', 'guarda_do_golpe', 'acelera',
  'golpe_do_potencial', 'braco_namekiano', 'punho_lendario', 'toque_da_destruicao', 'soco_casual', 'punho_amaldicoado', 'desmanche', 'soco_relampago', 'kusanagi', 'soco_de_chakra', 'chute_demoniaco', 'saque_do_trovao', 'laminas_serrilhadas', 'kunai_de_hiraishin', 'leque_gunbai', 'rinnegan', 'laminas_odm', 'soco_titanico', 'garras_de_killua', 'punho_transmutado', 'estalo_de_dedos', 'matadora_de_dragoes', 'soco_do_stand', 'soco_da_vida', 'pancada_de_sangue', 'dedo_apontado', 'golpe_de_panico', 'golpe_do_espiao', 'agulha_de_espinho', 'adaga_de_kamish', 'kagune', 'carta_magica', 'meteoros_de_pegaso', 'punho_do_dragao', 'corrente_de_andromeda', 'rendicao', 'chama_do_triangulo', 'soco_de_aco', 'teia_e_soco', 'bracelete', 'manopla', 'magia_do_caos', 'soco_de_pym', 'punho_fotonico', 'corrente_flamejante', 'toque_absorvente', 'golpe_psiquico', 'tentaculo_simbionte', 'lamina_viva', 'adaga_ilusoria', 'toque_do_devorador', 'arma_grande', 'tridente', 'garras_cineticas', 'punho_de_apokolips', 'mao_da_perdicao', 'masamune', 'laminas_do_caos', 'espada_mestra', 'rebellion_e_ebony', 'corte_dimensional', 'cqc', 'golpe_sobre_humano', 'lamina_oculta', 'spin_attack', 'z_saber', 'pisada_do_mario', 'chute_relampago', 'chute_do_dragao', 'soco_do_diabo', 'keyblade', 'aparar_e_cortar', 'lamina_protetica', 'frostmourne', 'arma_da_gravidade', 'grande_faca', 'adaga_do_tempo', 'espada_de_alucard', 'sais', 'nunchakus', 'bicada', 'golpe_alienigena', 'soco_de_marinheiro', 'machado_de_energon', 'karate', 'laco', 'fogo_azul', 'bigorna', 'frigideira', 'cajado_da_caveira', 'espada_de_augurio', 'barrigada', 'gadget_surpresa', 'raio_fantasma', 'flor_de_lapela', 'taco_de_beisebol', 'mordida_cartoon', 'soco_basico', 'chute_basico', 'susanoo_perfeito', 'meteoro_madara', 'mugen_tsukuyomi', 'sharingan_kakashi', 'raikiri', 'kamui', 'soco_espiritual', 'ritmo_eletrico', 'velocidade_divina', 'golpe_ascendente', 'postura_de_guarda', 'omnislash', 'soco_giratorio', 'batida_do_gorila', 'clones_naruto', 'rasengan', 'modo_kurama', 'golpe_fantasma', 'renascimento', 'gomu_gatling', 'corpo_de_borracha', 'gear_fifth_nika', 'visao_sismica', 'muralha_de_terra', 'metal_dobrado', 'jajanken_pedra', 'jajanken_tesoura', 'escudo_do_mentor', 'regeneracao_namekiana', 'garra_de_dragao', 'eu_te_seguro', 'ultimo_filho_de_krypton', 'zero_absoluto', 'soco_do_hulk', 'hulk_esmaga', 'rugido_do_hulk', 'mais_forte_ainda', 'velocidade_da_luz', 'ceifadora_de_almas', 'erguer_os_mortos', 'praga_da_carne', 'dobra_de_agua', 'estado_avatar_aang', 'controle_de_chakra', 'forca_monstruosa', 'byakugou']);

/** Bons para o ataque básico do personagem (quando ele já usa a família numa habilidade). */
export const NOVAS_DE_BASICO = new Set<FamiliaNova>(['garras', 'chicote', 'corrente', 'bastao', 'mordida', 'tentaculos', 'florete', 'lamina_de_fogo',
  'lamina_eletrica', 'lamina_sombria', 'lamina_de_agua', 'motosserra', 'espadao', 'iaido', 'chute_voador', 'bonk', 'pow_cartoon',
  'flecha', 'facas', 'espingarda']);
