/*
 * Que efeito cada habilidade usa, escolhido uma a uma.
 *
 * As regras por palavra (vfxProfiles.ts) acertam o tema, mas com 250 lutadores
 * metade das habilidades caía em "corte", "soco" ou "escudo". Aqui cada
 * habilidade marcante ganha a família que conta a história dela: o Azul do
 * Gojo puxa, o Vermelho empurra, o Vazio Infinito abre um domínio; o Hakai
 * desintegra; o Chidori canta; a Galick Gun é uma onda de ki. O que não está
 * aqui (marcado com "-") continua com a regra por palavra.
 *
 * Cada linha: as famílias das habilidades 0, 1 e 2 do personagem.
 */
import type { VfxFamily } from './vfxProfiles';

const T: Record<string, string> = {
  goku: 'kamehameha kaioken instinto', vegeta: 'kamehameha transformacao -', naruto: 'clones esfera_espiral manto_kurama',
  sasuke: 'chidori chama_negra hipnose', luffy: 'gatling esticar gear_fifth', gojo: 'atracao repulsao dominio',
  light: 'olho marca death_note', pikachu: '- raio_em_cadeia velocidade', saitama: '- resgate soco_serio',
  wolverine: 'garras armadura regeneracao', batman: 'marca disco escudo_tech', superman: 'laser resgate -',
  spiderman: 'teia resgate teia', hulk: '- rugido punho_gigante', thor: 'martelo tempestade raio_em_cadeia',
  strange: 'barreira_magica relogio portal', flash: '- resgate velocidade', wonderwoman: 'chicote escudo_fisico investida',
  ironman: 'feixe escudo_tech canhao_de_energia', captain: 'disco escudo_fisico grito_de_guerra', magneto: 'metal metal gravidade',
  deadpool: 'pow_cartoon confusao regeneracao', raven: 'runas sombra asa_negra', thanos: 'plasma relogio desintegrar',
  gohan: 'pilar grito_de_guerra kamehameha', piccolo: 'marca esticar regeneracao', frieza: 'disco laser transformacao',
  kakashi: 'olho chidori clones', itachi: 'lua_vermelha corvos susanoo', sakura: 'pisao punho_gigante cura_em_area',
  tanjiro: 'marca lamina_de_agua lamina_de_fogo', nezuko: 'sangue labareda transformacao', zenitsu: 'iaido velocidade lamina_eletrica',
  inosuke: 'olho garras investida', muzan: 'tentaculos acido regeneracao', yuji: 'punho_divergente faisca_negra -',
  megumi: 'inv_cao tempestade -', nobara: 'facas maldicao explosao', sukuna: 'mil_cortes corte_vertical mil_cortes',
  ichigo: '- transformacao lamina_sombria', rukia: 'espinho_de_gelo nevasca bloco_de_gelo', aizen: 'hipnose sarcofago olho',
  kenpachi: 'espadao corte_vertical transformacao', eren: 'punho_gigante armadura rugido', mikasa: 'investida - iaido',
  levi: 'marca - -', gon: 'punho_gigante corte_vertical hadouken', killua: 'clones raio raio_em_cadeia',
  hisoka: 'esticar cartas teia', kurapika: 'corrente corrente olho', edward: 'espinhos_de_terra runas metal',
  alphonse: 'armadura cura_em_area barreira_magica', roy: 'sopro_de_fogo chuva_de_meteoros labareda', guts: 'espadao armadura -',
  griffith: 'marca grito_de_guerra asa_negra', jotaro: 'inv_ora rajada_de_golpes relogio', dio: 'muda facas relogio',
  giorno: 'vinhas barreira_magica cura_em_area', denji: 'motosserra sangue mil_cortes', power: '- martelo sangue',
  makima: 'olho corrente hipnose', frieren: 'runas laser encanto', anya: 'olho resgate -',
  loid: 'clones silencio velocidade', yor: 'facas chute_voador petalas', jinwoo: 'invocacao grito_de_guerra inv_sombras',
  kaneki: 'tentaculos mordida tentaculos', yugi: 'cartas inv_mago runas', kaiba: 'canhao_de_energia inv_dragao supernova',
  blackpanther: 'armadura garras repulsao', scarletwitch: 'sorte - fenda', vision: 'teleporte laser pulso_emp',
  antman: 'atracao enxame punho_gigante', captainmarvel: 'cosmico hadouken supernova', daredevil: 'marca bastao bastao',
  punisher: 'marca espingarda tiro_preciso', ghostrider: 'corrente olho labareda', blade: 'marca iaido -',
  moonknight: 'lua disco raio_divino', storm: 'tornado raio_em_cadeia tempestade', cyclops: 'onda_de_energia laser -',
  jeangrey: '- barreira_magica fenix', rogue: '- - clones', gambit: 'cartas cartas bastao',
  professorx: 'olho hipnose silencio', venom: 'tentaculos mordida tentaculos', carnage: 'garras sangue mil_cortes',
  doctordoom: 'laser pentagrama canhao_de_energia', loki: 'clones teleporte hipnose', ultron: 'pulso_emp escudo_tech laser',
  greengoblin: 'bomba gas foguete', silversurfer: 'cosmico velocidade fenda', galactus: '- cosmico buraco_negro',
  starlord: 'esfera grito_de_guerra confete', groot: 'vinhas regeneracao vinhas', rocket: 'bomba foguete espingarda',
  aquaman: 'jato_dagua agua tsunami', greenlantern: 'escudo_fisico punho_gigante martelo', cyborg: 'pulso_emp canhao_de_energia laser',
  shazam: 'raio_divino grito_de_guerra encanto', cloud: 'corte_vertical escudo_fisico mil_cortes', tifa: 'exposto - -',
  sephiroth: 'iaido lamina_sombria asa_negra', kratos: 'lamina_de_fogo rugido labareda', link: '- escudo_fisico -',
  zelda: 'selo barreira_magica flecha', ganondorf: 'faisca_negra runas raio_divino', samus: 'marca missil esfera_carregada',
  dante: 'espadao saraivada transformacao', vergil: 'iaido fenda mil_cortes', bayonetta: 'chute_giratorio relogio inv_gomorrah',
  masterchief: 'escudo_tech saraivada pisao', doomslayer: 'investida armadura espinhos_de_terra', snake: 'teleporte tiro_preciso silencio',
  raidenmgr: 'lamina_eletrica mil_cortes iaido', leon: '- tiro_preciso corte_vertical', jill: 'cura grito_de_guerra armadura',
  wesker: 'teleporte rajada_de_golpes olho', lara: 'flecha - tiro_preciso', ezio: 'clones florete -',
  sonic: 'spin_dash resgate transformacao', shadowhh: 'flecha relogio chuva_de_meteoros', megaman: 'hadouken plasma esfera_carregada',
  zeromm: 'lamina_eletrica iaido mil_cortes', mario: 'bonk - estrela_invencivel', bowser: 'investida sopro_de_fogo pisao',
  ryu: 'hadouken shoryuken canhao_de_energia', chunli: '- chute_giratorio repulsao', akuma: 'hadouken teleporte shun_goku_satsu',
  scorpion: 'chicote teleporte sopro_de_fogo', subzero: '- bloco_de_gelo nevasca', liukang: 'chute_voador - dragao',
  raidenmk: 'tempestade barreira_magica raio_divino', jin: '- chute_voador asa_negra', kazuya: 'pisao laser transformacao',
  sora: '- - grito_de_guerra', tuob: 'corte_giratorio laser espadao', sekiro: 'escudo_fisico iaido execucao',
  malenia: '- mil_cortes petalas', agent47: 'clones chicote tiro_preciso', arthas: 'foice invocacao -',
  geralt: 'barreira_magica sopro_de_fogo hipnose', isaac: 'laser lentidao corte_vertical', gordon: 'bastao telecinese repulsao',
  hayabusa: 'iaido tornado esmagar', pyramidhead: 'espadao medo -', kirby: 'atracao encanto tornado',
  donkeykong: 'punho_gigante canhao -', simonbelmont: 'chicote agua_benta disco', princeofpersia: 'florete relogio areia',
  alucardcv: '- teleporte caveira', seiya: 'rajada_de_golpes cosmico investida', majinbuu: 'laser regeneracao pow_cartoon',
  kuririn: 'disco clarao_solar kamehameha', shiryu: 'escudo_fisico dragao pilar', hyoga: 'nevasca bloco_de_gelo bloco_de_gelo',
  shun: 'corrente tornado corrente', ikki: 'fenix hipnose renascer', saga: 'cosmico fenda hipnose',
  shaka: 'olho barreira_magica dominio', aiolia: 'plasma raio_em_cadeia rugido', camus: 'nevasca bloco_de_gelo espinho_de_gelo',
  hadescz: 'dominio medo caveira', madara: 'susanoo chuva_de_meteoros lua_vermelha', pain: 'gravidade repulsao buraco_negro',
  minato: 'teleporte esfera_espiral marca', gaara: 'areia areia areia', trunks: 'mil_cortes hadouken corte_vertical',
  cell: '- regeneracao supernova', broly: 'esfera_carregada transformacao rugido', beerus: 'desintegrar - repulsao',
  mewtwo: '- barreira_magica hipnose', charizard: 'sopro_de_fogo garras labareda', garou: 'lamina_de_agua chute_giratorio garras',
  genos: 'canhao_de_energia foguete pulso_emp', yusuke: 'punho_gigante hadouken espingarda', hiei: 'lamina_de_fogo olho dragao',
  sailormoon: 'disco purificacao ressurreicao', coringa: 'gas cartas bomba', arlequina: 'marretada chute_giratorio bomba',
  darkseid: 'laser punho_gigante hipnose', lexluthor: 'canhao radiacao enfraquecimento', spawn: 'corrente tentaculos labareda',
  invencivel: '- velocidade pow_cartoon', omniman: 'punho_gigante investida sangue', leonardo: '- grito_de_guerra investida',
  raphael: 'florete investida pow_cartoon', donatello: 'bastao pulso_emp escudo_tech', michelangelo: '- chute_giratorio confete',
  constantine: 'pentagrama raio_divino caveira', hellboy: 'punho_gigante armadura martelo', picapau: 'confusao florete confusao',
  pernalonga: 'teleporte clones bonk', ben10: '- labareda investida', aang: 'rajada_de_ar lamina_de_agua estado_avatar',
  samuraijack: 'iaido purificacao corte_vertical', heman: 'espadao tenho_a_forca espadao', popeye: 'pow_cartoon lanche rajada_de_golpes',
  optimus: 'escudo_tech laser grito_de_guerra', salsicha: 'velocidade lanche bonk', bobesponja: 'bolhas esticar chute_voador',
  scooby: 'bonk lanche sorte', rick: 'portal pulso_emp radiacao', finn: '- investida confete',
  megatron: 'canhao_de_energia punho_gigante medo', docinho: 'investida - supernova', mickey: 'encanto inv_vassouras confete',
  donald: 'pow_cartoon rugido -', pateta: 'bonk confusao sorte', stitch: '- mordida pow_cartoon',
  buzz: 'laser pulso_emp foguete', woody: 'chicote grito_de_guerra confete', srincrivel: 'investida escudo_fisico punho_gigante',
  mulherelastica: 'esticar escudo_fisico resgate', frozone: '- bloco_de_gelo nevasca', korra: 'sopro_de_fogo espinhos_de_terra estado_avatar',
  zuko: 'lamina_de_fogo raio_em_cadeia corte_cruzado', azula: 'labareda - florete', toph: '- espinhos_de_terra metal',
  iroh: 'lanche raio_em_cadeia sopro_de_fogo', patolino: 'confusao mordida bomba', taz: 'tornado mordida atracao',
  coiote: 'bomba bonk foguete', papaleguas: 'investida areia velocidade', marvin: 'bomba laser desintegrar',
  tom: 'pow_cartoon investida garras', jerry: 'bonk teleporte marretada', pantera: 'silencio clones teleporte',
  shredder: 'garras investida mil_cortes', splinter: '- bastao bonk', krang: 'inv_androide escudo_tech -',
  caseyjones: 'bastao - pow_cartoon', bebop: 'investida armadura pisao', skeletor: 'caveira - dominio',
  shera: 'raio_divino grito_de_guerra chute_voador', liono: 'espadao olho tempestade', cheetara: 'bastao investida florete',
  mummra: 'invocacao transformacao sarcofago', homer: 'bonk lanche pow_cartoon', bart: 'tiro confusao bomba',
  peter: 'pow_cartoon bomba confusao', stewie: 'laser escudo_tech dominio', cartman: 'rugido enfraquecimento gas',
  billcipher: 'runas fenda olho', plankton: 'inv_clones pulso_emp -', mojojojo: 'punho_gigante laser rugido',
  capitaoplaneta: 'barreira_magica vinhas grito_de_guerra', bugiganga: 'esticar rajada_de_ar confusao', dannyphantom: 'laser teleporte rugido',
  coragem: 'medo resgate bencao',
};

export const FAMILIA_DA_HABILIDADE: Record<string, VfxFamily> = Object.fromEntries(
  Object.entries(T).flatMap(([id, linha]) => linha.split(' ').flatMap((f, i) => (f === '-' ? [] : [[`${id}:${i}`, f as VfxFamily]]))),
);

/*
 * A criatura de cada invocador (parte 8): a mesma animação e o mesmo som quando
 * ela chega (a habilidade) e a cada ataque dela. O Caminho Deva do Pain segue
 * com a gravidade; o Caminho Animal aparece nos ataques da invocação.
 */
export const FAMILIA_DA_INVOCACAO: Record<string, VfxFamily> = {
  megumi: 'inv_cao', jinwoo: 'inv_sombras', yugi: 'inv_mago', kaiba: 'inv_dragao', bayonetta: 'inv_gomorrah',
  jotaro: 'inv_ora', pain: 'inv_feras', mickey: 'inv_vassouras', plankton: 'inv_clones', krang: 'inv_androide',
};

/*
 * O ataque básico com nome próprio (src/data/basicos.ts) usa o efeito que bate
 * com o nome: o Escudo arremessado do Capitão voa e quica, a Martelada do Thor
 * é martelo, o Dardo crescente do Cavaleiro da Lua é disco, as kunais do
 * Kakashi e do Minato são facas, o Estilingue do Bart é tiro.
 *
 * O ataque básico de quem tem um jeito próprio de bater: o espadachim corta, o
 * atirador atira, o telepata empurra com a mente. Os outros seguem a regra
 * (as próprias habilidades e o visual do personagem).
 */
export const FAMILIA_DO_BASICO: Record<string, VfxFamily> = {
  akuma: 'soco',
  agent47: 'tiro_preciso',
  arthas: 'frostmourne',
  geralt: 'corte_diagonal',
  donkeykong: 'golpe_pesado',
  beerus: 'toque_da_destruicao',
  yusuke: 'rei_gun',
  constantine: 'runas',
  aang: 'rajada_de_ar',
  rick: 'laser',
  azula: 'fogo_azul',
  iroh: 'sopro_de_fogo',
  papaleguas: 'investida',
  marvin: 'laser',
  pantera: 'bonk',
  skeletor: 'cajado_da_caveira',
  shera: 'corte_diagonal',
  billcipher: 'chama_do_triangulo',
  dannyphantom: 'raio_fantasma',
  naruto: 'combo_dos_clones',
  batman: 'batarangue',
  spiderman: 'teia_e_soco',
  deadpool: 'corte_cruzado',
  frieza: 'laser',
  inosuke: 'laminas_serrilhadas',
  aizen: 'corte',
  hisoka: 'cartas',
  kurapika: 'corrente',
  griffith: 'florete',
  jotaro: 'soco_do_stand',
  makima: 'dedo_apontado',
  frieren: 'feitico_comum',
  jinwoo: 'adaga_de_kamish',
  scarletwitch: 'magia_do_caos',
  storm: 'vento',
  cyclops: 'feixe',
  jeangrey: 'telecinese',
  professorx: 'golpe_psiquico',
  loki: 'adaga_ilusoria',
  aquaman: 'tridente',
  cloud: 'espadao',
  samus: 'canhao_de_braco',
  bayonetta: 'saraivada',
  wesker: 'golpe_sobre_humano',
  sonic: 'spin_attack',
  shadowhh: 'flecha',
  megaman: 'mega_buster',
  luffy: 'esticar',
  light: 'olho',
  thor: 'martelo',
  flash: 'soco_relampago',
  wonderwoman: 'bracelete',
  captain: 'escudo_do_capitao',
  magneto: 'metal',
  thanos: 'manopla',
  kakashi: 'facas',
  itachi: 'shuriken',
  nezuko: 'chute_demoniaco',
  megumi: 'sombra',
  levi: 'corte_giratorio',
  killua: 'garras_de_killua',
  alphonse: 'golpe_pesado',
  yugi: 'carta_magica',
  kaiba: 'carta_dragao',
  vision: 'laser',
  punisher: 'tiro',
  moonknight: 'disco',
  gambit: 'cartas',
  doctordoom: 'laser',
  ultron: 'laser',
  greengoblin: 'bomba',
  silversurfer: 'feixe',
  starlord: 'blasters_elementais',
  groot: 'vinhas',
  greenlantern: 'punho_gigante',
  cyborg: 'canhao_sonico',
  shazam: 'raio',
  tifa: 'rajada_de_golpes',
  zelda: 'luz',
  ganondorf: 'faisca_negra',
  masterchief: 'saraivada',
  doomslayer: 'espingarda',
  leon: 'tiro',
  jill: 'tiro',
  lara: 'duas_pistolas',
  bowser: 'garras',
  isaac: 'cortador_de_plasma',
  gordon: 'arma_da_gravidade',
  kirby: 'atracao',
  seiya: 'meteoros_de_pegaso',
  kuririn: 'kamehameha',
  hyoga: 'po_de_diamante',
  saga: 'explosao',
  shaka: 'rendicao',
  aiolia: 'raio',
  camus: 'gelo',
  hadescz: 'lamina_sombria',
  minato: 'kunai_de_hiraishin',
  gaara: 'areia',
  cell: 'tentaculos',
  mewtwo: 'telecinese',
  genos: 'fogo',
  sailormoon: 'tiara_lunar',
  coringa: 'flor_de_lapela',
  arlequina: 'taco_de_beisebol',
  lexluthor: 'laser',
  optimus: 'machado_de_energon',
  scooby: 'mordida_cartoon',
  megatron: 'canhao_de_energia',
  mickey: 'encanto',
  stitch: 'garras',
  buzz: 'laser',
  mulherelastica: 'esticar',
  korra: 'fogo',
  tom: 'frigideira',
  krang: 'laser',
  bebop: 'investida',
  mummra: 'sombra',
  bart: 'estilingue',
  stewie: 'laser',
  cartman: 'pow_cartoon',
  plankton: 'laser',
  mojojojo: 'laser',
  capitaoplaneta: 'raio_de_gaia',
  coragem: 'mordida_cartoon',
  vegeta: 'rajada_continua',
  goku: 'ki_dourado',
  taz: 'tornado',
  gohan: 'golpe_do_potencial',
  piccolo: 'braco_namekiano',
  broly: 'punho_lendario',
  saitama: 'soco_casual',
  gojo: 'infinito',
  yuji: 'punho_amaldicoado',
  sukuna: 'desmanche',
  pikachu: 'choque_do_pikachu',
  sasuke: 'kusanagi',
  sakura: 'soco_de_chakra',
  zenitsu: 'saque_do_trovao',
  nobara: 'martelo_e_prego',
  madara: 'leque_gunbai',
  pain: 'rinnegan',
  mikasa: 'laminas_odm',
  eren: 'soco_titanico',
  gon: 'jajanken',
  edward: 'punho_transmutado',
  roy: 'estalo_de_dedos',
  guts: 'matadora_de_dragoes',
  giorno: 'soco_da_vida',
  power: 'pancada_de_sangue',
  anya: 'golpe_de_panico',
  loid: 'golpe_do_espiao',
  yor: 'agulha_de_espinho',
  kaneki: 'kagune',
  shiryu: 'punho_do_dragao',
  shun: 'corrente_de_andromeda',
  ikki: 'punho_da_fenix',
  charizard: 'garra_flamejante',
  superman: 'soco_de_aco',
  strange: 'disparo_arcano',
  ironman: 'repulsor',
  raven: 'corvo_da_alma',
  antman: 'soco_de_pym',
  captainmarvel: 'punho_fotonico',
  ghostrider: 'corrente_flamejante',
  rogue: 'toque_absorvente',
  venom: 'tentaculo_simbionte',
  carnage: 'lamina_viva',
  galactus: 'toque_do_devorador',
  rocket: 'arma_grande',
  blackpanther: 'garras_cineticas',
  darkseid: 'punho_de_apokolips',
  hellboy: 'mao_da_perdicao',
  sephiroth: 'masamune',
  kratos: 'laminas_do_caos',
  link: 'espada_mestra',
  dante: 'rebellion_e_ebony',
  vergil: 'corte_dimensional',
  snake: 'cqc',
  ezio: 'lamina_oculta',
  zeromm: 'z_saber',
  mario: 'pisada_do_mario',
  chunli: 'chute_relampago',
  scorpion: 'kunai_do_inferno',
  liukang: 'chute_do_dragao',
  kazuya: 'soco_do_diabo',
  sora: 'keyblade',
  sekiro: 'aparar_e_cortar',
  malenia: 'lamina_protetica',
  pyramidhead: 'grande_faca',
  princeofpersia: 'adaga_do_tempo',
  alucardcv: 'espada_de_alucard',
  raphael: 'sais',
  michelangelo: 'nunchakus',
  picapau: 'bicada',
  patolino: 'bicada',
  ben10: 'golpe_alienigena',
  popeye: 'soco_de_marinheiro',
  bobesponja: 'karate',
  woody: 'laco',
  coiote: 'bigorna',
  liono: 'espada_de_augurio',
  homer: 'barrigada',
  bugiganga: 'gadget_surpresa',
};
