import { describe,it,expect } from 'vitest';
import { createBattle,simulate,applyEffects,updateDominion } from '../src/engine/battle';
import { createDirection,advanceDirection,type Direction } from '../src/presentation/director';
import { PRESENTATION as P } from '../src/presentation/config';
import { DOMINION as D } from '../src/engine/dominion-config';
const a=['goku','pikachu','captain'],b=['vegeta','raven','hulk'];
function watch(d:Direction,speed:(frame:number)=>number){let frames=0,maxQueue=0;while(!d.complete&&frames<60000){advanceDirection(d,.04*speed(frames++));maxQueue=Math.max(maxQueue,d.queue.length);}expect(d.complete).toBe(true);expect(maxQueue).toBeLessThanOrEqual(12);return frames*.04;}
describe('Direção sem alterar regras',()=>{
 it('mantém a apresentação desacoplada do passo de simulação',()=>{expect(P.normalSeconds).toBeGreaterThan(1);expect(P.skillSeconds).toBeGreaterThan(P.normalSeconds);expect(P.grandSeconds).toBeGreaterThan(P.skillSeconds);expect(P.renderIntervalMs).toBe(40);});
 it('1×, 2× e troca no meio reproduzem exatamente a mesma batalha e eventos',()=>{const one=createDirection(createBattle(a,b,42)),two=createDirection(createBattle(a,b,42)),changed=createDirection(createBattle(a,b,42));const duration1=watch(one,()=>1),duration2=watch(two,()=>2);watch(changed,f=>f%300<150?1:2);expect(one.battle).toEqual(simulate(a,b,42));expect(two.battle).toEqual(one.battle);expect(changed.battle).toEqual(one.battle);expect(Math.abs(duration1-2*duration2)).toBeLessThan(.09);expect(one.visible).toEqual(one.battle);expect(one.active).toBe(null);});
 it('o relógio da batalha avança 10 segundos enquanto os efeitos visuais seguem em paralelo',()=>{
  const battle=createBattle(a,b,0x101),direction=createDirection(battle);
  for(const fighter of battle.fighters){fighter.hp=1e8;fighter.maxHp=1e8;}
  advanceDirection(direction,10);
  expect(direction.battle.time).toBeCloseTo(10,6);
  expect(direction.battle.finished).toBe(false);
  expect(direction.queue.length).toBeLessThanOrEqual(12);
 });
 it('mostra a consequência somente no impacto e termina a última ação antes do resultado',()=>{const battle=createBattle(a,b,2);battle.fighters[0].action=1;battle.fighters.filter(f=>f.side==='enemy').forEach(f=>{f.hp=1;});const d=createDirection(battle);while(!d.active)advanceDirection(d,.01);const beat=d.active!;const target=beat.event.target!;expect(beat.impacted).toBe(false);expect(d.visible.fighters.find(f=>f.uid===target)!.hp).toBe(beat.before.fighters.find(f=>f.uid===target)!.hp);advanceDirection(d,beat.duration*P.impactAt);expect(beat.impacted).toBe(true);expect(d.visible.fighters.find(f=>f.uid===target)!.hp).toBe(beat.after.fighters.find(f=>f.uid===target)!.hp);watch(d,()=>2);expect(d.visible.finished).toBe(true);expect(d.visible).toEqual(battle);});
 it('pausa sem avanço e segue até 120 segundos com vitória por Domínio',()=>{const battle=createBattle(a,b,8);for(const f of battle.fighters){f.maxHp=1e8;f.hp=f.side==='enemy'?8e7:1e8;}const expected=structuredClone(battle),d=createDirection(battle);advanceDirection(d,0);expect(battle).toEqual(expected);watch(d,()=>2);expect(battle.time).toBe(120);expect(battle.reason).toBe('Vantagem de Domínio');expect(battle.winner).toBe('player');});
 it('emite pronta também quando carga direta de aliado completa uma habilidade',()=>{const battle=createBattle(a,b,9),target=battle.fighters[1];target.skills[0].charge=95;applyEffects(battle,battle.fighters[0],[target],[{kind:'charge',value:10}]);expect(target.skills[0].charge).toBe(100);expect(battle.events.find(e=>e.kind==='ready')).toMatchObject({source:target.uid,skill:0});});
 it('informa a origem real de um bloqueio e a habilidade beneficiada por sinergia',()=>{const battle=createBattle(['light','pikachu','wolverine'],b,9),[light,pika,wolverine,attacker]=battle.fighters;applyEffects(battle,wolverine,[light],[{kind:'shield',value:100}]);applyEffects(battle,attacker,[light],[{kind:'damage',value:60}]);expect(battle.events.find(e=>e.kind==='block')).toMatchObject({source:wolverine.uid,target:light.uid,attacker:attacker.uid,value:60});applyEffects(battle,pika,[attacker],[{kind:'status',status:'paralyzed',value:1,duration:2}]);expect(battle.events.find(e=>e.kind==='synergy'&&e.target===light.uid)).toHaveProperty('skill');});
 it('dá impulso por incapacitação, mas conserva memória e inércia do Domínio',()=>{const battle=createBattle(['pikachu','light','wolverine'],b,10),enemy=battle.fighters[3];battle.dominion=60;battle.lastLead='player';applyEffects(battle,enemy,[battle.fighters[0]],[{kind:'damage',value:1000}]);expect(battle.fighters[0].hp).toBe(0);expect(battle.momentum).toBeLessThan(-D.event.knockout);updateDominion(battle);expect(battle.dominion).toBeGreaterThan(0);for(let i=0;i<80;i++)updateDominion(battle);expect(battle.dominion).toBeLessThan(0);});
 it('não pontua cura desperdiçada nem escudo ainda não usado',()=>{const battle=createBattle(['wolverine','captain','light'],b,11),[wolverine,captain,light]=battle.fighters;applyEffects(battle,wolverine,[wolverine],[{kind:'heal',value:200}]);applyEffects(battle,captain,[light],[{kind:'shield',value:200}]);expect(battle.momentum).toBe(0);light.hp-=150;applyEffects(battle,wolverine,[light],[{kind:'heal',value:100}]);expect(battle.momentum).toBeGreaterThan(0);});
});
