import { useState } from 'react';
import { Search,ArrowUpRight,Users,Zap,Swords,Orbit,RotateCcw,Eye,Shield,HeartPulse,Volume2,SlidersHorizontal,Gamepad2,CircleHelp,ChevronRight } from 'lucide-react';
import { characters,byId } from '../data/characters';
import { Portrait } from '../components/Portrait';
import { SkillIcon } from '../components/Icon';
import { StatusBadge } from '../components/StatusBadge';
import { statuses } from '../data/statuses';
import { presentStatus,positiveStatuses } from '../engine/skill-descriptions';
import { rolesFor,roleOrder,type Role } from '../presentation/roles';
import type { Settings } from '../lib/storage';

export function CharactersScreen({onDetails}:{onDetails:(id:string)=>void}){
  const [query,setQuery]=useState(''),[universe,setUniverse]=useState('Todos'),[role,setRole]=useState<Role|'Todas'>('Todas'),[focused,setFocused]=useState(''),[visibleCount,setVisibleCount]=useState(24);
  const filtered=characters.filter(c=>(universe==='Todos'||c.universe===universe)&&(role==='Todas'||rolesFor(c).includes(role))&&`${c.name} ${c.universe}`.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')));
  const featured=filtered.find(c=>c.id===focused)??filtered[0];
  const update=()=>setVisibleCount(24);
  return <section className="roster-screen"><div className="screen-title"><span className="eyebrow">{characters.length} PERSONAGENS · INFINITAS COMBINAÇÕES</span><h1>Encontre quem muda sua luta.</h1><p>Explore funções e habilidades. Toque em um lutador para ver a ficha.</p></div>
    <div className="roster-filters"><label className="search"><Search size={18}/><input aria-label="Buscar personagem" placeholder="Buscar personagem…" value={query} onChange={e=>{setQuery(e.target.value);update();}}/></label><select value={universe} onChange={e=>{setUniverse(e.target.value);update();}} aria-label="Filtrar universo">{['Todos',...new Set(characters.map(c=>c.universe))].map(u=><option key={u}>{u}</option>)}</select><select value={role} onChange={e=>{setRole(e.target.value as Role|'Todas');update();}} aria-label="Filtrar função">{['Todas',...roleOrder].map(u=><option key={u}>{u}</option>)}</select></div>
    {featured&&<div className="roster-showcase" style={{'--character':featured.color} as React.CSSProperties}><div className="showcase-portrait"><Portrait character={featured}/></div><div className="showcase-copy"><span className="eyebrow">LUTADOR EM DESTAQUE · {featured.universe}</span><h2>{featured.name}</h2><p>{featured.idea}</p><div className="role-chips">{rolesFor(featured).map(role=><span key={role}>{role}</span>)}</div><div className="showcase-skills">{featured.skills.map(s=><span key={s.id} title={s.name}><SkillIcon type={s.icon} characterId={featured.id} skillId={s.id}/><small>{s.name}</small></span>)}</div><button className="secondary" onClick={()=>onDetails(featured.id)}>Abrir ficha <ArrowUpRight size={16}/></button></div></div>}
    {filtered.length>1&&<div className="roster-picks"><small>TOQUE PARA DESTACAR</small><div>{filtered.slice(0,6).map(c=><button key={c.id} className={featured?.id===c.id?'active':''} onClick={()=>setFocused(c.id)} aria-label={`Destacar ${c.name}`}><Portrait character={c}/><span>{c.name}</span></button>)}</div></div>}
    <div className="roster-count"><strong>{filtered.length}</strong> lutadores encontrados <span>· toque numa carta para abrir sua ficha</span></div>
    <div className="roster-grid">{filtered.slice(0,visibleCount).map(c=><button className={`roster-card ${featured?.id===c.id?'spotlighted':''}`} key={c.id} onPointerEnter={()=>setFocused(c.id)} onFocus={()=>setFocused(c.id)} onClick={()=>onDetails(c.id)} style={{'--character':c.color} as React.CSSProperties}><Portrait character={c}/><span className="roster-arrow"><ArrowUpRight size={17}/></span><div><span className="mini-label">{c.universe}</span><h3>{c.name}</h3><p>{c.idea}</p><div className="role-chips">{rolesFor(c).map(role=><span key={role}>{role}</span>)}</div><div className="roster-skills">{c.skills.map(s=><SkillIcon key={s.id} type={s.icon} size={17} characterId={c.id} skillId={s.id}/>)}</div><small>Ver ficha →</small></div></button>)}</div>
    {filtered.length>visibleCount&&<button className="secondary roster-more" onClick={()=>setVisibleCount(n=>n+24)}>Ver mais lutadores <ChevronRight size={17}/></button>}
    {!filtered.length&&<p className="empty-state">Nenhum personagem encontrado. Experimente outro nome, universo ou função.</p>}
  </section>;
}

const demos=[
  {title:'Ataque básico',detail:'O círculo enche. O lutador age e o alvo recebe o impacto.',icon:Swords},
  {title:'Carga',detail:'A habilidade enche de 0% a 100%. Quando fica pronta, o ícone acende.',icon:Zap},
  {title:'Preparo',detail:'Uma habilidade começou, mas ainda pode ser interrompida.',icon:Orbit},
  {title:'Escudo',detail:'A barreira absorve o impacto antes da Vida.',icon:Shield},
  {title:'Status',detail:'O efeito chega ao alvo e seu ícone permanece enquanto durar.',icon:HeartPulse},
  {title:'Vantagem',detail:'O medidor reage à luta. Algumas habilidades dependem dele; a vitória não.',icon:Users},
] as const;
function DemoArt({index}:{index:number}){
  if(index===0)return <div className="demo-art demo-attack"><div className="demo-actor"><Portrait character={byId.goku}/><i/></div><span className="demo-travel">→</span><div className="demo-victim"><Portrait character={byId.vegeta}/><b>−66</b></div></div>;
  if(index===1)return <div className="demo-art demo-charge"><SkillIcon type={byId.goku.skills[0].icon} characterId="goku" skillId={byId.goku.skills[0].id} size={51}/><div><span>CARGA DA HABILIDADE</span><i/><strong>100% · PRONTA</strong></div></div>;
  if(index===2)return <div className="demo-art demo-prep"><div className="prep-portrait"><Portrait character={byId.goku}/><i/></div><div><strong>PREPARANDO</strong><span>Kamehameha</span><small>Pode ser interrompido</small></div></div>;
  if(index===3)return <div className="demo-art demo-shield"><Shield size={58}/><div><span>ESCUDO</span><strong>180 bloqueado</strong><i/></div></div>;
  if(index===4)return <div className="demo-art demo-status"><Portrait character={byId.vegeta}/><span>→</span><StatusBadge status={{id:'exposed',remaining:8,duration:8,intensity:.22,source:''}}/><strong>EXPOSTO</strong></div>;
  return <div className="demo-art demo-advantage"><span>RIVAIS</span><div><i/></div><span>SEU TRIO</span><strong>VIRADA!</strong></div>;
}
export function HelpScreen({onPlay}:{onPlay:()=>void}){
  const [active,setActive]=useState(0);
  const example=(id:keyof typeof statuses)=>characters.flatMap(c=>[...c.basic.effects,...c.trait.effects,...c.skills.flatMap(s=>s.effects)]).find(e=>e.kind==='status'&&e.status===id);
  const groups=[{title:'Começar',icon:Users,items:[['Trio','Escolha 3 personagens. Eles lutam automaticamente.'],['Jornada','Vença 10 confrontos. Uma derrota encerra a jornada.']]},{title:'Batalha',icon:Swords,items:[['Vida','Quando chega a zero, o personagem sai da luta.'],['Ataque básico','O círculo do retrato mostra quando será o próximo ataque.'],['Escudo','Absorve dano antes da Vida.'],['Interrupção','Cancela ou atrasa uma habilidade durante o Preparo.']]},{title:'Habilidades',icon:Zap,items:[['Carga','Cada habilidade vai de 0% a 100%. Com 100%, fica pronta.'],['Preparo','Tempo entre começar a habilidade e ela acontecer. Pode ser interrompido.'],['Recarga','Tempo depois do uso antes de voltar ao ciclo.']]},{title:'Vantagem',icon:Orbit,items:[['Vantagem','Mostra quem controla a luta. Algumas habilidades reagem quando o trio está à frente ou atrás. Não decide a vitória.'],['Sinergia','Quando a ação de um aliado ajuda outro personagem.'],['Inteligência','Mostra a qualidade das decisões automáticas, de 0 a 100.']]}];
  return <section className="help-screen"><div className="screen-title"><span className="eyebrow">GUIA VISUAL</span><h1>Aprenda vendo a luta.</h1><p>Escolha uma mecânica. A demonstração mostra onde olhar durante a batalha.</p></div>
    <div className="help-demo-shell"><div className="help-demo-tabs">{demos.map((demo,i)=><button key={demo.title} className={active===i?'active':''} onClick={()=>setActive(i)}><demo.icon size={16}/>{demo.title}</button>)}</div><div className="help-demo-stage" key={active}><DemoArt index={active}/><div className="demo-explanation"><span>0{active+1} / 06</span><h2>{demos[active].title}</h2><p>{demos[active].detail}</p></div></div></div>
    <div className="help-sections">{groups.map(group=><section className="help-group" key={group.title}><h2><group.icon size={22}/>{group.title}</h2><div className="help-items">{group.items.map(([name,description])=><article key={name}><strong>{name}</strong><p>{description}</p>{name==='Carga'&&<div className="charge-demo"><span>0%</span><i/><b>100% · PRONTA</b></div>}</article>)}</div></section>)}{(['positivo','negativo'] as const).map(tone=><section className="help-group" key={tone}><h2>Status {tone==='positivo'?'positivos':'negativos'}</h2><div className="status-legend"><div>{Object.keys(statuses).filter(id=>positiveStatuses.has(id as keyof typeof statuses)===(tone==='positivo')).map(id=>{const key=id as keyof typeof statuses,raw=example(key),value=raw?.kind==='status'?raw.value:0;return <span key={id}><StatusBadge status={{id:key,remaining:10,duration:10,intensity:value,source:''}}/><strong>{statuses[key].name}</strong><small>{presentStatus(key,value).summary}</small></span>})}</div></div></section>)}</div>
    <button className="secondary review-tutorial" onClick={()=>{try{localStorage.removeItem('nexus-battle-guide-v1')}catch{return}}}><Eye size={16}/> Rever guia na próxima batalha</button><button className="primary" onClick={onPlay}>Montar meu trio <ArrowUpRight size={19}/></button>
  </section>;
}

export function SettingsScreen({settings:s,onChange,onReset}:{settings:Settings;onChange:(s:Settings)=>void;onReset:()=>void}){
  const [confirm,setConfirm]=useState(false);
  return <section className="settings-screen"><div className="screen-title"><span className="eyebrow">DO SEU JEITO</span><h1>Prepare sua experiência.</h1><p>Suas preferências ficam salvas neste dispositivo.</p></div>
    <div className="settings-list">
      <section className="settings-panel"><h2 className="settings-group"><Volume2 size={20}/> Áudio</h2><div className="setting-row"><div><h3>Volume</h3><p>Volume geral da trilha e dos efeitos de batalha.</p></div><input aria-label="Volume" type="range" min="0" max="100" value={s.volume} onChange={e=>onChange({...s,volume:Number(e.target.value)})}/></div>{([{key:'musicVolume',title:'Música de batalha',text:'Trilha original procedural. Baixo, percussão e sintetizadores.'},{key:'effectsVolume',title:'Efeitos sonoros',text:'Ações, proteção, interrupções e grandes viradas.'}] as const).map(x=><label className="setting-row" key={x.key}><div><h3>{x.title}</h3><p>{x.text}</p></div><input aria-label={x.title} type="range" min="0" max="100" value={s[x.key]} onChange={e=>onChange({...s,[x.key]:Number(e.target.value)})}/></label>)}</section>
      <section className="settings-panel"><h2 className="settings-group"><SlidersHorizontal size={20}/> Visual</h2>{([{key:'effects',title:'Efeitos visuais',text:'Raios, ondas e efeitos das habilidades.'},{key:'numbers',title:'Números de combate',text:'Dano, cura, Escudo e bloqueio aparecem sobre os alvos.'},{key:'reducedMotion',title:'Reduzir movimento',text:'Mantém fonte e alvo destacados, sem deslocamentos rápidos.'}] as const).map(x=><label className="setting-row" key={x.key}><div><h3>{x.title}</h3><p>{x.text}</p></div><input className="toggle" type="checkbox" checked={s[x.key]} onChange={e=>onChange({...s,[x.key]:e.target.checked})}/></label>)}</section>
      <section className="settings-panel"><h2 className="settings-group"><Gamepad2 size={20}/> Jogo</h2><div className="setting-row"><div><h3>Velocidade padrão</h3><p>A mesma simulação, no seu ritmo.</p></div><div className="segmented">{([1,2] as const).map(n=><button key={n} className={s.speed===n?'active':''} onClick={()=>onChange({...s,speed:n})}>{n}×</button>)}</div></div><label className="setting-row"><div><h3>Sequência automática</h3><p>Começa o próximo confronto após uma vitória.</p></div><input className="toggle" type="checkbox" checked={s.auto} onChange={e=>onChange({...s,auto:e.target.checked})}/></label></section>
      <section className="settings-panel"><h2 className="settings-group"><CircleHelp size={20}/> Ajuda</h2><div className="setting-row"><div><h3>Ajuda na batalha</h3><p>Mostra a legenda e dicas para entender habilidades e Status.</p></div><div className="segmented">{(['normal','detailed','off'] as const).map(mode=><button key={mode} className={s.explanations===mode?'active':''} onClick={()=>onChange({...s,explanations:mode})}>{mode==='normal'?'Normal':mode==='detailed'?'Detalhada':'Desligada'}</button>)}</div></div><button className="secondary review-tutorial" onClick={()=>{try{localStorage.removeItem('nexus-battle-guide-v1')}catch{return}}}><Eye size={16}/> Rever tutorial na próxima batalha</button></section>
    </div>
    <div className="reset-box"><div><h3>Recomeçar do zero</h3><p>Apaga jornada, recordes e preferências deste dispositivo.</p></div>{confirm?<div className="reset-confirm"><button className="danger" onClick={onReset}>Apagar dados locais</button><button className="secondary" onClick={()=>setConfirm(false)}>Cancelar</button></div>:<button className="secondary" onClick={()=>setConfirm(true)}><RotateCcw size={16}/>Resetar dados</button>}</div>
  </section>;
}
