import { useState } from 'react';
import { Search,ArrowUpRight,Users,Shuffle,Zap,Timer,Orbit,FastForward,RotateCcw,Eye } from 'lucide-react';
import { characters } from '../data/characters';
import { Portrait } from '../components/Portrait';
import { SkillIcon } from '../components/Icon';
import { StatusBadge } from '../components/StatusBadge';
import { statuses } from '../data/statuses';
import type { Settings } from '../lib/storage';
export function CharactersScreen({onDetails}:{onDetails:(id:string)=>void}){
  const [query,setQuery]=useState(''),[universe,setUniverse]=useState('Todos');
  const filtered=characters.filter(c=>(universe==='Todos'||c.universe===universe)&&`${c.name} ${c.universe}`.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'').includes(query.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g,'')));
  return <section className="roster-screen"><div className="screen-title"><span className="eyebrow">{characters.length} PERSONAGENS · NOVAS POSSIBILIDADES</span><h1>Lendas que se conectam.</h1><p>Conheça cada habilidade. Encontre a próxima combinação.</p></div><div className="roster-filters"><label className="search"><Search size={18}/><input aria-label="Buscar personagem" placeholder="Buscar personagem…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select value={universe} onChange={e=>setUniverse(e.target.value)} aria-label="Filtrar universo">{['Todos',...new Set(characters.map(c=>c.universe))].map(u=><option key={u}>{u}</option>)}</select></div><div className="roster-grid">{filtered.map(c=><button className="roster-card" key={c.id} onClick={()=>onDetails(c.id)} style={{'--character':c.color} as React.CSSProperties}><Portrait character={c}/><span className="roster-arrow"><ArrowUpRight size={17}/></span><div><span className="mini-label">{c.universe}</span><h3>{c.name}</h3><p>{c.idea}</p><div className="roster-skills">{c.skills.map(s=><SkillIcon key={s.id} type={s.icon} size={17} characterId={c.id} skillId={s.id}/>)}</div></div></button>)}</div>{!filtered.length&&<p className="empty-state">Nenhum personagem encontrado. Experimente outro nome ou universo.</p>}</section>;
}
export function HelpScreen({onPlay}:{onPlay:()=>void}){
 const [effectsOpen,setEffectsOpen]=useState(false);
 const steps=[{icon:Users,title:'Três escolhas. Um trio.',text:'Escolha um entre três candidatos por rodada. Combine proteção, controle e impacto. O mesmo trio acompanha toda a jornada.'},{icon:Shuffle,title:'Três chances de mudar.',text:'Use até três pulos durante toda a seleção. Cada pulo troca os candidatos sem gastar uma escolha.'},{icon:Orbit,title:'Leia os círculos.',text:'O anel do retrato enche até a próxima ação normal. Os três ícones abaixo carregam habilidades; quando prontas, elas agem sozinhas ou esperam a oportunidade.'},{icon:Zap,title:'Perceba as conexões.',text:'Uma linha verde entre aliados mostra carga recebida. Um retrato brilhando anuncia uma preparação. Interromper ou proteger esse momento pode mudar tudo.'},{icon:Timer,title:'Dois minutos. Um Domínio.',text:'Incapacite os três rivais para vencer. Se o tempo acabar, a barra única de Domínio decide: Condição, controle, cura e proteção úteis contam. Empates usam Condição total, integrantes ativos e contribuição útil.'},{icon:FastForward,title:'Acelere sua jornada.',text:'Use 1× ou 2× e pause quando quiser. Após vencer, avance ao próximo confronto. A Condição é restaurada entre lutas. Uma derrota encerra a jornada; a décima vitória faz seu trio campeão.'}];
 return <section className="help-screen"><div className="screen-title"><span className="eyebrow">FÁCIL DE COMEÇAR. DIVERTIDO DE DESCOBRIR.</span><h1>A estratégia vem antes da luta.</h1><p>Você escolhe a conexão. Seu trio faz o resto.</p></div><div className="help-grid">{steps.map((s,i)=><article key={s.title}><s.icon size={26}/><span className="mini-label">0{i+1}</span><h2>{s.title}</h2><p>{s.text}</p></article>)}</div><div className="skill-legend"><span><i className="legend-empty"/>Vazio</span><span><i className="legend-charging"/>Carregando</span><span><i className="legend-ready"/>Pronto</span><span><i className="legend-executing"/>Executando</span><span><i className="legend-cooldown"/>Recarga</span></div><button className="secondary effects-legend-toggle" aria-expanded={effectsOpen} onClick={()=>setEffectsOpen(!effectsOpen)}><Eye size={15}/>{effectsOpen?'Fechar efeitos':`Ver efeitos · ${Object.keys(statuses).length}`}</button>{effectsOpen&&<div className="status-legend"><h2>Efeitos ativos</h2><div>{Object.entries(statuses).map(([id,s])=><span key={id}><StatusBadge status={{id:id as keyof typeof statuses,remaining:10,duration:10,intensity:0,source:''}}/>{s.name}<small>{s.description}</small></span>)}</div></div>}<button className="secondary review-tutorial" onClick={()=>{try{localStorage.removeItem('nexus-battle-guide-v1')}catch{return}}}><Eye size={16}/> Rever guia visual na próxima batalha</button><button className="primary" onClick={onPlay}>Montar meu trio <ArrowUpRight size={19}/></button></section>;
}
export function SettingsScreen({settings:s,onChange,onReset}:{settings:Settings;onChange:(s:Settings)=>void;onReset:()=>void}){
  const [confirm,setConfirm]=useState(false);
  return <section className="settings-screen"><div className="screen-title"><span className="eyebrow">DO SEU JEITO</span><h1>Configurações.</h1><p>Suas preferências ficam salvas neste dispositivo.</p></div><div className="settings-list"><div className="setting-row"><div><h3>Volume</h3><p>Volume geral da trilha e dos efeitos de batalha.</p></div><input aria-label="Volume" type="range" min="0" max="100" value={s.volume} onChange={e=>onChange({...s,volume:Number(e.target.value)})}/></div>{([{key:'musicVolume',title:'Música de batalha',text:'Trilha original procedural. Baixo, percussão e sintetizadores.'},{key:'effectsVolume',title:'Efeitos sonoros',text:'Ações, proteção, interrupções e grandes viradas.'}] as const).map(x=><label className="setting-row" key={x.key}><div><h3>{x.title}</h3><p>{x.text}</p></div><input aria-label={x.title} type="range" min="0" max="100" value={s[x.key]} onChange={e=>onChange({...s,[x.key]:Number(e.target.value)})}/></label>)}{([{key:'effects',title:'Efeitos visuais',text:'Raios, ondas e conexões entre aliados.'},{key:'numbers',title:'Números de dano',text:'Mostra valores sobre os retratos durante a luta.'},{key:'reducedMotion',title:'Reduzir movimento',text:'Desativa tremores, pulsações e deslocamentos.'},{key:'auto',title:'Sequência automática',text:'Começa a próxima batalha após uma vitória.'}] as const).map(x=><label className="setting-row" key={x.key}><div><h3>{x.title}</h3><p>{x.text}</p></div><input className="toggle" type="checkbox" checked={s[x.key]} onChange={e=>onChange({...s,[x.key]:e.target.checked})}/></label>)}<div className="setting-row"><div><h3>Explicações durante a luta</h3><p>Mostra por que habilidades recebem carga.</p></div><div className="segmented">{(['normal','detailed','off'] as const).map(mode=><button key={mode} className={s.explanations===mode?'active':''} onClick={()=>onChange({...s,explanations:mode})}>{mode==='normal'?'Normal':mode==='detailed'?'Detalhada':'Desligada'}</button>)}</div></div><div className="setting-row"><div><h3>Velocidade padrão</h3><p>A mesma simulação, no seu ritmo.</p></div><div className="segmented">{([1,2] as const).map(n=><button key={n} className={s.speed===n?'active':''} onClick={()=>onChange({...s,speed:n})}>{n}×</button>)}</div></div></div><div className="reset-box"><div><h3>Recomeçar do zero</h3><p>Apaga jornada, recordes e preferências deste dispositivo.</p></div>{confirm?<div className="reset-confirm"><button className="danger" onClick={onReset}>Apagar dados locais</button><button className="secondary" onClick={()=>setConfirm(false)}>Cancelar</button></div>:<button className="secondary" onClick={()=>setConfirm(true)}><RotateCcw size={16}/>Resetar dados</button>}</div></section>;
}
