import { ArrowUpRight,ArrowRight,Trophy,CircleHelp,Settings2,Download,ChevronRight,Users,Swords } from 'lucide-react';
import { byId } from '../data/characters';
import { Portrait } from '../components/Portrait';
import type { Profile, Run } from '../lib/storage';
interface Props {profile:Profile;run:Run|null;onPlay:()=>void;onContinue:()=>void;onAbandon:()=>void;onNavigate:(s:'characters'|'help'|'settings')=>void;onInstall:()=>void}
export function Home({profile,run,onPlay,onContinue,onAbandon,onNavigate,onInstall}:Props){
  const hasRun=!!run,terminal=run?.stage==='result'&&(run.battle?.winner!=='player'||run.index===9);
  const progress=run?.index??0,wonCurrent=run?.stage==='result'&&run.battle?.winner==='player';
  return <section className="game-hub">
    <div className="hub-hero"><div><span className="eyebrow">{hasRun?'JORNADA EM ANDAMENTO':'SUA PRÓXIMA JORNADA'}</span><h1>{hasRun?terminal?'Veja como seu trio se saiu.':`Confronto ${progress+1} de 10`:'Monte um trio. Entre na arena.'}</h1><p>{hasRun?run?.stage==='draft'?'Escolha seus três personagens para começar.':terminal?'Seu resultado está pronto.':`Próximo desafio: ${run?.encounters[progress]?.name}`:'Escolha três personagens. Eles lutam automaticamente; você descobre o que a combinação consegue fazer.'}</p><button className="primary hero-cta" onClick={hasRun?onContinue:onPlay}>{terminal?'Ver resultado':hasRun?'Continuar jornada':'Montar meu trio'}<ArrowUpRight size={20}/></button>{hasRun&&!terminal&&<button className="abandon-campaign" onClick={onAbandon}>Desistir desta jornada</button>}</div>
      <div className="hub-team"><span className="eyebrow">{run?.team.length?'SEU TRIO':profile.champion?.length?'ÚLTIMO TRIO CAMPEÃO':'O QUE VEM AÍ'}</span><div>{(run?.team.length?run.team:profile.champion?.length?profile.champion:['goku','pikachu','gojo']).map(id=>{const c=byId[id];return <span key={id} style={{'--character':c.color} as React.CSSProperties}><Portrait character={c}/><strong>{c.name}</strong></span>})}</div></div>
    </div>
    <div className="hub-progress"><div className="section-heading"><div><span className="eyebrow">TRILHA DA JORNADA</span><h2>{hasRun?`${progress+(wonCurrent?1:0)} vitórias nesta jornada`:'Dez confrontos até o título'}</h2></div><span className="record">RECORDE <strong>{profile.best}<small>/10</small></strong></span></div><div className="milestones">{Array.from({length:10},(_,i)=><div className={`${hasRun?i<progress+(wonCurrent?1:0):i<profile.best?'complete':''} ${hasRun&&i===progress&&!terminal?'next':''}`} key={i} aria-label={`Confronto ${i+1}${hasRun&&i===progress&&!terminal?', próximo':''}`}>{i===9?<Trophy size={17}/>:String(i+1).padStart(2,'0')}</div>)}</div><div className="journey-bottom"><span>{profile.journeys} jornadas · {profile.victories} trios campeões</span><button className="text-button" onClick={onPlay}>Nova jornada <ArrowRight size={15}/></button></div></div>
    <div className="hub-links"><button onClick={()=>onNavigate('characters')}><Users size={20}/><span><b>Personagens</b><small>Conheça os 100 lutadores</small></span><ChevronRight size={17}/></button><button onClick={()=>onNavigate('help')}><CircleHelp size={20}/><span><b>Como jogar</b><small>Aprenda a ler a batalha</small></span><ChevronRight size={17}/></button><button onClick={()=>onNavigate('settings')}><Settings2 size={20}/><span><b>Configurações</b><small>Áudio, visual e jogo</small></span><ChevronRight size={17}/></button><button onClick={onInstall}><Download size={20}/><span><b>Instalar</b><small>Leve seu trio com você</small></span><ChevronRight size={17}/></button></div>
    <p className="hub-rule"><Swords size={17}/> A vitória acontece quando o trio rival inteiro sai da luta.</p>
  </section>;
}
