import { ArrowRight,RotateCcw,Shield,Swords,Zap,Home,Trophy,Star } from 'lucide-react';
import type { Run } from '../lib/storage';
import { byId } from '../data/characters';
import { Portrait } from '../components/Portrait';
import { AuxIcon } from '../components/Icon';
import { summarizeBattle,summarizeRun } from '../engine/run-summary';

export function ResultScreen({run,onNext,onRestart,onAbandon,onHome,auto,onAuto}:{run:Run;onNext:()=>void;onRestart:()=>void;onAbandon:()=>void;onHome:()=>void;auto:boolean;onAuto:(v:boolean)=>void}){
  const b=run.battle!,won=b.winner==='player',champion=won&&run.index===9;
  const journey=champion||!won?summarizeRun(run.summaries?.length?run.summaries:[summarizeBattle(run.index,b)]):null;
  const fmt=(value:number)=>Math.round(value).toLocaleString('pt-BR');
  const fighters=b.fighters.filter(f=>f.side==='player');
  const damage=[...fighters].sort((a,z)=>z.stats.damage-a.stats.damage)[0];
  const support=[...fighters].sort((a,z)=>(z.stats.protection+z.stats.healing)-(a.stats.protection+a.stats.healing))[0];
  const control=[...fighters].sort((a,z)=>z.stats.interrupts-a.stats.interrupts)[0];
  const mvp=[...fighters].sort((a,z)=>(z.stats.damage+z.stats.healing+z.stats.protection+z.stats.interrupts*100+z.stats.kills*100)-(a.stats.damage+a.stats.healing+a.stats.protection+a.stats.interrupts*100+a.stats.kills*100))[0];
  const lastKo=b.events.filter(e=>e.kind==='ko').at(-1);
  const combatant=(uid:string)=>b.fighters.find(f=>f.uid===uid);
  const moment=lastKo?`${byId[combatant(lastKo.source)?.characterId??'']?.name??'O trio'} tirou ${byId[combatant(lastKo.target??'')?.characterId??'']?.name??'um rival'} da luta.`:won?'Seu trio resistiu até o último rival sair da arena.':'O trio rival levou a melhor neste confronto.';
  const totals=run.team.map(id=>({id,stats:journey?.battles.flatMap(x=>x.fighters).filter(f=>f.characterId===id).reduce((sum,f)=>({damage:sum.damage+f.damage,healing:sum.healing+f.healing,protection:sum.protection+f.protection,interrupts:sum.interrupts+f.interrupts,kills:sum.kills+f.kills}),{damage:0,healing:0,protection:0,interrupts:0,kills:0})}));
  const nameFor=(uid:string)=>byId[run.team[Number(uid.split('-')[1])]]?.name??'Aliado';
  return <section className={`result-screen game-result ${champion?'champion':''} ${won?'victory':'defeat'}`}>
    <div className="result-hero"><div className="result-rays" aria-hidden="true"/><div className="result-medal"><AuxIcon id={won?'victory':'defeat'} size={55}/></div><span className="eyebrow">{champion?'DEZ CONFRONTOS. UM TRIO CAMPEÃO.':`CONFRONTO ${String(run.index+1).padStart(2,'0')} / 10`}</span><h1>{champion?'TRIO CAMPEÃO':won?'VITÓRIA':'DERROTA'}</h1><p>{champion?'Seu trio venceu a jornada inteira.':won?`${run.encounters[run.index].name} superado. O próximo confronto está liberado.`:`Sua jornada terminou no confronto ${run.index+1}. O que seu trio conquistou fica registrado.`}</p>
      <div className="winning-trio">{run.team.map(id=><div key={id}><Portrait character={byId[id]}/><h3>{byId[id].name}</h3></div>)}</div>
      <div className="result-progress"><span>{won?'TRILHA AVANÇOU':'TRILHA ENCERRADA'}</span><div>{Array.from({length:10},(_,i)=><i key={i} className={`${i<run.index+(won?1:0)?'won':''} ${i===run.index&&!won?'lost':''} ${i===run.index+1&&won&&!champion?'next':''}`}>{i===9?<Trophy size={11}/>:i+1}</i>)}</div><strong>{run.index} / 10 → {run.index+(won?1:0)} / 10</strong></div>
    </div>
    <div className="result-moment"><Star size={20}/><span><small>MOMENTO DECISIVO</small><strong>{moment}</strong></span></div>
    <div className="highlights"><article className="mvp"><Star size={20}/><span>MVP DO CONFRONTO</span><div className="highlight-portrait"><Portrait character={byId[mvp.characterId]}/></div><h3>{byId[mvp.characterId].name}</h3><p>{mvp.stats.kills} eliminações · {fmt(mvp.stats.damage)} de dano</p></article><article><Swords size={21}/><span>MAIOR DANO</span><div className="highlight-portrait"><Portrait character={byId[damage.characterId]}/></div><h3>{byId[damage.characterId].name}</h3><div className="highlight-meter"><i style={{width:`${Math.max(7,100*damage.stats.damage/Math.max(1,fighters.reduce((n,f)=>n+f.stats.damage,0)))}%`}}/></div><p>{fmt(damage.stats.damage)} de dano</p></article>{support.stats.protection+support.stats.healing>0?<article><Shield size={21}/><span>MAIOR APOIO</span><div className="highlight-portrait"><Portrait character={byId[support.characterId]}/></div><h3>{byId[support.characterId].name}</h3><div className="highlight-meter support"><i style={{width:`${Math.max(7,100*(support.stats.protection+support.stats.healing)/Math.max(1,fighters.reduce((n,f)=>n+f.stats.protection+f.stats.healing,0)))}%`}}/></div><p>{fmt(support.stats.protection)} bloqueado · {fmt(support.stats.healing)} curado</p></article>:control.stats.interrupts>0?<article><Zap size={21}/><span>MELHOR CONTROLE</span><div className="highlight-portrait"><Portrait character={byId[control.characterId]}/></div><h3>{byId[control.characterId].name}</h3><p>{control.stats.interrupts} interrupções ou atrasos</p></article>:null}</div>
    {control.stats.interrupts>0&&support.stats.protection+support.stats.healing>0&&<p className="result-control"><Zap size={14}/>{byId[control.characterId].name} interrompeu ou atrasou {control.stats.interrupts} preparos rivais.</p>}
    {won&&!champion&&<div className="result-next"><span className="eyebrow">PRÓXIMO DESAFIO DESBLOQUEADO</span><h2>{run.encounters[run.index+1].name}</h2><div>{run.encounters[run.index+1].team.map(id=><span key={id}><Portrait character={byId[id]}/><small>{byId[id].name}</small></span>)}</div></div>}
    {journey&&<section className="journey-summary" aria-label="Resumo da jornada"><div className="journey-score"><div><small>JORNADA {champion?'CONCLUÍDA':'ENCERRADA'}</small><strong>{journey.won} de 10 vitórias</strong></div><div><small>PONTUAÇÃO</small><strong>{fmt(journey.score)}</strong></div><div className="journey-rank"><small>DESEMPENHO</small><strong>{journey.rank}</strong></div></div>
      <div className="journey-metrics"><span><b>{fmt(journey.damage)}</b> dano</span><span><b>{fmt(journey.healing)}</b> cura</span><span><b>{fmt(journey.protection)}</b> bloqueado</span><span><b>{journey.interrupts}</b> interrupções</span><span><b>{journey.kills}</b> eliminações</span></div>
      <h2>O que cada um trouxe</h2><div className="journey-contributors">{totals.map(({id,stats})=><article key={id}><Portrait character={byId[id]}/><div><strong>{byId[id].name}</strong><span>{fmt(stats?.damage??0)} dano · {fmt((stats?.healing??0)+(stats?.protection??0))} apoio</span><small>{stats?.interrupts??0} interrupções · {stats?.kills??0} eliminações</small></div><i style={{width:`${Math.min(100,100*(stats?.damage??0)/Math.max(1,journey.damage))}%`}}/></article>)}</div>
      <h2>Conexões e aprendizados</h2><div className="journey-lessons">{journey.topSynergy&&<p><b>{nameFor(journey.topSynergy.source)} ajudou {nameFor(journey.topSynergy.target)}</b> a deixar habilidades prontas {journey.topSynergy.count} vezes.</p>}{journey.lessons.filter(line=>!journey.topSynergy||!line.startsWith('A ligação mais frequente')).slice(0,2).map(line=><p key={line}>{line}</p>)}</div>
      <h2>A trilha que seu trio percorreu</h2><ol className="journey-battles">{journey.battles.map(item=><li key={item.index} className={item.won?'won':'lost'}><span>{String(item.index+1).padStart(2,'0')}</span><div><strong>{item.won?'VITÓRIA':'DERROTA'}</strong><small>{item.survivors} do trio permaneceram na luta</small></div><div className="journey-opponents">{item.enemies.map(id=><Portrait key={id} character={byId[id]}/>)}</div></li>)}</ol>
    </section>}
    <div className="result-actions">{won&&!champion?<><button className="primary" onClick={onNext}>Próxima batalha <ArrowRight size={19}/></button><button className="danger" onClick={onAbandon}>Desistir da jornada</button></>:<button className="primary" onClick={onRestart}>Montar outro trio <RotateCcw size={19}/></button>}<button className="secondary" onClick={onHome}><Home size={17}/>Início</button></div>
    {won&&!champion&&<label className="auto-label result-auto"><input type="checkbox" checked={auto} onChange={e=>onAuto(e.target.checked)}/>{auto?'Próxima batalha em instantes · desmarque para parar':'Avançar automaticamente entre batalhas'}</label>}
  </section>;
}
