import { createRequire } from 'node:module';
import { mkdirSync,writeFileSync } from 'node:fs';
import { createServer } from 'vite';
const server=await createServer({server:{host:'127.0.0.1',port:5173,strictPort:true}});await server.listen();
const require=createRequire(import.meta.url);
process.env.PLAYWRIGHT_BROWSERS_PATH??='/tmp/nexus-browsers';
const {chromium}=require('@playwright/test');
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const page=await browser.newPage({viewport:{width:1440,height:1080},deviceScaleFactor:1});
await page.clock.install();
const issues=[];page.on('pageerror',e=>issues.push(e.message));page.on('console',e=>{if(e.type()==='error')issues.push(e.text());});
mkdirSync('test-results',{recursive:true});
await page.goto('http://127.0.0.1:5173',{waitUntil:'networkidle'});
await page.screenshot({path:'test-results/home-desktop.png',fullPage:true});
await page.setViewportSize({width:390,height:844});
await page.screenshot({path:'test-results/home-mobile.png',fullPage:true});
await page.getByRole('button',{name:'Montar meu trio',exact:true}).click();
await page.getByRole('button',{name:'Trocar candidatos'}).click();
await page.screenshot({path:'test-results/draft-mobile.png',fullPage:true});
for(let i=0;i<3;i++)await page.getByRole('button',{name:'Escolher',exact:true}).first().click();
await page.getByRole('button',{name:'Entrar na arena'}).click();
await page.waitForTimeout(1400);
await page.getByRole('button',{name:'Pausar',exact:true}).click();
const before=await page.locator('.battle-clock strong').innerText();
await page.waitForTimeout(400);
if(await page.locator('.battle-clock strong').innerText()!==before)throw Error('Pausa não congelou o relógio');
if(await page.locator('[data-fighter]').count()!==6)throw Error('Faltam integrantes');
await page.screenshot({path:'test-results/battle-mobile.png',fullPage:true});
await page.setViewportSize({width:1440,height:1080});
await page.screenshot({path:'test-results/battle-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Velocidade 1 vezes',exact:true}).click();
await page.reload({waitUntil:'networkidle'});
await page.getByRole('button',{name:'Continuar jornada',exact:true}).click();
if(!await page.getByRole('button',{name:'Velocidade 2 vezes',exact:true}).count())throw Error('Velocidade não persistiu');
await page.getByRole('button',{name:'Continuar',exact:true}).click();
for(let i=0;i<12&&!await page.locator('.result-screen').count();i++)await page.clock.runFor(45000);
await page.waitForTimeout(100);
if(!await page.locator('.result-screen').count())throw Error('Não chegou ao resultado');
await page.screenshot({path:'test-results/result-desktop.png',fullPage:true});
await page.getByRole('button',{name:'Início',exact:true}).last().click();
await page.getByRole('button',{name:'Personagens 24'}).click();
if(await page.locator('.roster-card').count()!==24)throw Error('Elenco incompleto');
await page.getByLabel('Buscar personagem').fill('Light');
await page.locator('.roster-card').click();
await page.getByRole('dialog').waitFor({state:'visible'});
if(!await page.getByRole('heading',{name:'Death Note',exact:true}).count())throw Error('Ficha incompleta');
await page.getByRole('button',{name:'Fechar detalhes'}).click();
await page.setViewportSize({width:390,height:844});
await page.getByLabel('Buscar personagem').fill('');
await page.screenshot({path:'test-results/roster-mobile.png',fullPage:true});
const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth);
if(overflow)throw Error('Overflow horizontal');
writeFileSync('test-results/browser-report.json',JSON.stringify({ok:true,issues,viewportChecks:['1440×1080','390×844'],checks:['draft skip','three picks','six fighters','pause','2x persisted','reload resume','real battle complete','24 characters','Light details','no horizontal overflow']},null,2));
console.log(JSON.stringify({ok:true,issues}));await browser.close();await server.close();
