import { createRequire } from 'node:module';
import { writeFileSync } from 'node:fs';
import { preview } from 'vite';
const server=await preview({preview:{host:'127.0.0.1',port:4173,strictPort:true}});
process.env.PLAYWRIGHT_BROWSERS_PATH??='/tmp/nexus-browsers';
const {chromium}=createRequire(import.meta.url)('@playwright/test');
const browser=await chromium.launch({headless:true,args:['--no-sandbox']});
const context=await browser.newContext({viewport:{width:390,height:844}});
const page=await context.newPage();await page.goto('http://127.0.0.1:4173',{waitUntil:'networkidle'});
await page.evaluate(()=>navigator.serviceWorker.ready);
await page.waitForFunction(()=>!!navigator.serviceWorker.controller);
const cache=await page.evaluate(async()=>{const names=await caches.keys();const opened=await caches.open(names.find(n=>n.startsWith('nexus-')));return (await opened.keys()).map(r=>new URL(r.url).pathname);});
if(!cache.includes('/index.html')||!cache.includes('/icon-192.png')||!cache.some(x=>x.endsWith('.js')))throw Error('Cache PWA incompleto');
const manifest=await page.evaluate(async()=>await(await fetch('/manifest.webmanifest')).json());
if(manifest.display!=='standalone'||manifest.icons.length<2)throw Error('Manifesto inválido');
await context.setOffline(true);await page.reload({waitUntil:'load'});
await page.getByRole('button',{name:'Montar meu trio',exact:true}).click();
for(let i=0;i<3;i++)await page.getByRole('button',{name:'Escolher',exact:true}).first().click();
await page.getByRole('button',{name:'Entrar na arena'}).click();
if(await page.locator('[data-fighter]').count()!==6)throw Error('Jogo indisponível offline');
await page.getByRole('button',{name:'Pausar',exact:true}).click();
await page.screenshot({path:'test-results/offline-battle.png',fullPage:true});
writeFileSync('test-results/pwa-report.json',JSON.stringify({ok:true,cachedFiles:cache.length,checks:['manifest standalone and PNG icons','service worker active','offline reload','offline draft','offline battle']},null,2));
console.log(JSON.stringify({ok:true,cachedFiles:cache.length}));await browser.close();server.httpServer.close();
